(function(g){var window=this;var Rya=function(a,b){return g.Ub(a,b)},d6=function(a){g.Bm(a,"zx",g.Ua());
return a},e6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Em(a.g,b,c)},Sya=function(a,b){var c=[];
g.kk(b,function(a){try{var b=g.ZC.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.YC(b)&&c.push(a):c.push(a)},a);
return c},Tya=function(a,b){var c=Sya(a,b);
(0,g.G)(c,function(a){g.ZC.prototype.remove.call(this,a)},a)},Uya=function(){var a=g.rG;
Tya(a,a.g.Xd(!0))},Vya=function(a,b,c,d){var e=new g.sm(null,void 0);
a&&g.tm(e,a);b&&g.um(e,b);c&&g.vm(e,c);d&&g.wm(e,d);return e},Wya=function(a){g.KF[a]&&(a=g.KF[a],(0,g.G)(a,function(a){g.IF[a]&&delete g.IF[a]}),a.length=0)},Xya=function(a){var b=g.HF();
if(b)if(b.clear(a),a)Wya(a);else for(var c in g.KF)Wya(c)},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.A=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.mm;this.g=this.o="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Yya(this,a.capabilities||""),Zya(this,a.experiments||""),this.o=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Yya=function(a,b){a.capabilities.clear();
(0,g.Id)(b.split(","),g.Da(Rya,$ya)).forEach(function(b){a.capabilities.add(b)})},Zya=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},aza=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bza=function(a){return new g6(a)},cza=function(a){return g.xa(a)?(0,g.H)(a,bza):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.xa(a)?"["+(0,g.H)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dza=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.eb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.eb(a,function(a){return h6(a,b)})},n6=function(){var a=g.uG("yt-remote-connected-devices")||[];
g.Db(a);return a},eza=function(a){if(g.kb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},fza=function(a){g.tG("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.uG("yt-remote-device-id");a||(a=k6(),g.tG("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.jb(a,b);g.zG()&&g.Fb(a,b);a=eza(a);if(g.kb(a))try{g.xG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.yG("remote_sid",a.join(","),-1)}catch(c){}},gza=function(){return g.uG("yt-remote-session-browser-channel")},hza=function(){return g.uG("yt-remote-local-screens")||[]},iza=function(){g.tG("yt-remote-lounge-token-expiration",!0,86400)},jza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(hza(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.am)(c,function(a){return!g.jb(b,a)})&&iza();
g.tG("yt-remote-local-screens",a,31536E3)},kza=function(a,b){g.tG("yt-remote-session-browser-channel",a);
g.tG("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.jb(c,d)||c.push(d);fza(c);q6()},r6=function(a){a||(g.vG("yt-remote-session-screen-id"),g.vG("yt-remote-session-video-id"));
q6();a=n6();g.rb(a,p6());fza(a)},lza=function(){if(!s6){var a=g.eD();
a&&(s6=new g.TC(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},mza=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ya(a)},nza=function(a,b){var c=g.Ad("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},oza=function(){var a=mza(),b=window.document.getElementById(a),c=b&&g.XE(b,"loaded");
c||b&&!c||(b=nza(a,function(){g.XE(b,"loaded")||(g.WE(b,"loaded","true"),g.OF(a),g.UD(g.Da(Xya,a),0))}))},pza=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?(0,window.parseInt)(a[1],10):0},t6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},qza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},rza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},x6=function(a){if(a>=sza.length)u6();
else{var b=sza[a],c="chrome-extension://"+b+tza;0<=v6.indexOf(b)?rza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,w6(c,u6)):x6(a+1)}):w6(c,function(){x6(a+1)})}},w6=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},y6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},u6=function(){var a=qza();
a&&a(!1,"No cast extension found")},vza=function(){if(uza){var a=2,b=qza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;w6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},wza=function(){if(y6("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){vza();a({command:"cast.sender.init"});return}}if(!window.chrome||y6("Edge"))u6();else if(vza(),y6("Android")&&y6("Chrome/")&&window.navigator.presentation){a="";var b=pza();55<=b?a="55":50<=b&&(a="50");w6("//www.gstatic.com/eureka/clank"+a+tza,u6)}else x6(0)},z6=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.qc=b;this.C=(0,g.z)(this.KH,this);this.g=!1;this.o=0;this.A=this.Aa=null;this.B=[]},A6=function(){},B6=function(a,b,c,d){this.g=a;
this.A=b;this.G=c;this.F=d||1;this.C=45E3;this.B=new g.Im(this);this.o=new g.og;this.o.setInterval(250)},yza=function(a,b,c){a.nj=1;
a.mh=d6(b.clone());a.Gi=c;a.D=!0;xza(a,null)},C6=function(a,b,c,d,e){a.nj=1;
a.mh=d6(b.clone());a.Gi=null;a.D=c;e&&(a.oC=!1);xza(a,d)},xza=function(a,b){a.Tj=(0,g.F)();
D6(a);a.Fh=a.mh.clone();e6(a.Fh,"t",a.F);a.Sl=0;a.Nc=a.g.Oq(a.g.Ml()?b:null);0<a.xr&&(a.Ro=new g.Ok((0,g.z)(a.vD,a,a.Nc),a.xr));a.B.U(a.Nc,"readystatechange",a.DS);var c=a.hi?g.ac(a.hi):{};a.Gi?(a.zp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Fh,a.zp,a.Gi,c)):(a.zp="GET",a.oC&&!g.wd&&(c.Connection="close"),a.Nc.send(a.Fh,a.zp,null,c));a.g.rf(1)},Bza=function(a,b,c){for(var d=!0;!a.Rh&&a.Sl<c.length;){var e=zza(a,c);
if(e==E6){4==b&&(a.nh=4,F6(15),d=!1);break}else if(e==Aza){a.nh=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.nh=1,F6(17),d=!1);a.vf=a.vf&&d;d||(H6(a),I6(a))},zza=function(a,b){var c=a.Sl,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return Aza;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Sl=d+c;return e},Dza=function(a,b){a.Tj=(0,g.F)();
D6(a);var c=b?window.location.hostname:"";a.Fh=a.mh.clone();g.Bm(a.Fh,"DOMAIN",c);g.Bm(a.Fh,"t",a.F);try{a.wf=new window.ActiveXObject("htmlfile")}catch(n){H6(a);a.nh=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in J6)k=J6[l];else if(l in Cza)k=J6[l]=Cza[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=J6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Yc(g.uc("b/12014412"),d);a.wf.open();a.wf.write(g.Qc(c));a.wf.close();a.wf.parentWindow.m=(0,g.z)(a.IR,a);a.wf.parentWindow.d=(0,g.z)(a.GB,a,!0);a.wf.parentWindow.rpcClose=(0,g.z)(a.GB,a,!1);c=a.wf.createElement("DIV");a.wf.parentWindow.document.body.appendChild(c);d=g.Gc(a.Fh.toString());d=g.Ma(g.Dc(d));d=g.Yc(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Qc(d);
a.g.rf(1)},D6=function(a){a.Wu=(0,g.F)()+a.C;
Eza(a,a.C)},Eza=function(a,b){if(null!=a.pk)throw Error("WatchDog timer not null");
a.pk=K6((0,g.z)(a.ZR,a),b)},L6=function(a){a.pk&&(g.w.clearTimeout(a.pk),a.pk=null)},I6=function(a){a.g.Rx()||a.Rh||a.g.Go(a)},H6=function(a){L6(a);
g.Ve(a.Ro);a.Ro=null;a.o.stop();g.Om(a.B);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.wf&&(a.wf=null)},G6=function(a,b){try{a.g.zB(a,b),a.g.rf(4)}catch(c){}},Gza=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Fza(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Gza(a,b,c,d,f)},f)})}},Fza=function(a,b,c){var d=new window.Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Hza=function(a){this.g=a;
this.o=new A6},Iza=function(a){var b=N6(a.g,a.tk,"/mail/images/cleardot.gif");
d6(b);Gza(b.toString(),5E3,(0,g.z)(a.TG,a),3,2E3);a.rf(1)},P6=function(a){var b=a.g.I;
if(null!=b)F6(5),b?(F6(11),O6(a.g,a,!1)):(F6(12),O6(a.g,a,!0));else if(a.oe=new B6(a,void 0,void 0,void 0),a.oe.hi=a.ur,b=a.g,b=N6(b,b.Ml()?a.Tk:null,a.wr),F6(5),!g.ud||g.qc(10))e6(b,"TYPE","xmlhttp"),C6(a.oe,b,!1,a.Tk,!1);else{e6(b,"TYPE","html");var c=a.oe;a=!!a.Tk;c.nj=3;c.mh=d6(b.clone());Dza(c,a)}},Q6=function(a,b,c){this.g=1;
this.o=[];this.B=[];this.C=new A6;this.G=a||null;this.I=null!=b?b:null;this.D=c||!1},Jza=function(a,b){this.g=a;
this.map=b;this.context=null},Kza=function(a){g.Xe.call(this,"statevent",a)},Lza=function(a,b){g.Xe.call(this,"timingevent",a);
this.size=b},Mza=function(a){g.Xe.call(this,"serverreachability",a)},Pza=function(a){Nza(a);
if(3==a.g){var b=a.Bl++,c=a.Cn.clone();g.Bm(c,"SID",a.A);g.Bm(c,"RID",b);g.Bm(c,"TYPE","terminate");R6(a,c);b=new B6(a,a.A,b,void 0);b.nj=2;b.mh=d6(c.clone());(new window.Image).src=b.mh;b.Tj=(0,g.F)();D6(b)}Oza(a)},Qza=function(a){a.rH(1,0);
a.Cn=N6(a,null,a.tr);S6(a)},Nza=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.kc&&(a.kc.cancel(),a.kc=null);a.vg&&(g.w.clearTimeout(a.vg),a.vg=null);T6(a);a.Nd&&(a.Nd.cancel(),a.Nd=null);a.dh&&(g.w.clearTimeout(a.dh),a.dh=null)},Rza=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.o.push(new Jza(a.KN++,b));2!=a.g&&3!=a.g||S6(a)},S6=function(a){a.Nd||a.dh||(a.dh=K6((0,g.z)(a.EB,a),0),a.fj=0)},Tza=function(a,b){if(1==a.g){if(!b){a.Bl=Math.floor(1E5*Math.random());
var c=a.Bl++,d=new B6(a,"",c,void 0);d.hi=null;var e=U6(a),f=a.Cn.clone();g.Bm(f,"RID",c);g.Bm(f,"CVER","1");R6(a,f);yza(d,f,e);a.Nd=d;a.g=2}}else 3==a.g&&(b?Sza(a,b):0==a.o.length||a.Nd||Sza(a))},Sza=function(a,b){if(b)if(6<a.Th){a.o=a.B.concat(a.o);
a.B.length=0;var c=a.Bl-1;var d=U6(a)}else c=b.G,d=b.Gi;else c=a.Bl++,d=U6(a);var e=a.Cn.clone();g.Bm(e,"SID",a.A);g.Bm(e,"RID",c);g.Bm(e,"AID",a.Bj);R6(a,e);c=new B6(a,a.A,c,a.fj+1);c.hi=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Nd=c;yza(c,e,d)},R6=function(a,b){if(a.pd){var c=a.pd.yx();
c&&g.Kb(c,function(a,c){g.Bm(b,c,a)})}},U6=function(a){var b=Math.min(a.o.length,1E3),c=["count="+b];
if(6<a.Th&&0<b){var d=a.o[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.o[e].g,k=a.o[e].map;f=6>=a.Th?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.B=a.B.concat(a.o.splice(0,b));
return c.join("&")},Uza=function(a){a.kc||a.vg||(a.F=1,a.vg=K6((0,g.z)(a.DB,a),0),a.Wi=0)},V6=function(a){if(a.kc||a.vg||3<=a.Wi)return!1;
a.F++;a.vg=K6((0,g.z)(a.DB,a),Vza(a,a.Wi));a.Wi++;return!0},O6=function(a,b,c){a.yp=c;
a.ff=b.Bg;a.D||Qza(a)},T6=function(a){null!=a.Vh&&(g.w.clearTimeout(a.Vh),a.Vh=null)},Vza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.pd&&(c=null);var d=(0,g.z)(a.xT,a);c||(c=new g.sm("//www.google.com/images/cleardot.gif"),d6(c));Fza(c.toString(),1E4,d)}else F6(2);Wza(a,b)},Wza=function(a,b){a.g=0;
a.pd&&a.pd.ww(b);Oza(a);Nza(a)},Oza=function(a){a.g=0;
a.ff=-1;if(a.pd)if(0==a.B.length&&0==a.o.length)a.pd.Dq();else{g.ub(a.B);var b=g.ub(a.o);a.B.length=0;a.o.length=0;a.pd.Dq(b)}},N6=function(a,b,c){var d=g.Cm(c);
if(""!=d.o)b&&g.um(d,b+"."+d.o),g.vm(d,d.C);else{var e=window.location;d=Vya(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Gk&&g.Kb(a.Gk,function(a,b){g.Bm(d,b,a)});
g.Bm(d,"VER",a.Th);R6(a,d);return d},K6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(a){X6.dispatchEvent(new Kza(X6,a))},Xza=function(){},Yza=function(a,b){this.action=a;
this.params=b||{}},Z6=function(a,b){g.L.call(this);
this.g=new g.Wt(this.A,0,this);g.M(this,this.g);this.o=this.qc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a;Y6(this)},Y6=function(a){a.g.stop();
a.qc=5E3+2E4*Math.random()},$6=function(a,b,c){this.L=a;
this.D=b;this.A=new g.SC;this.o=new Z6(this.cU,this);this.g=this.Za=null;this.J=!1;this.C=null;this.I="";this.G=this.B=0;this.F=[];this.N=c||!1},Zza=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.yp,sessionId:a.g.A,arrayId:a.g.Bj}},$za=function(a,b){a.G=b||0;
a.o.stop();a.g&&(3==a.g.g&&Tza(a.g),Pza(a.g));a.G=0},a7=function(a){return!!a.g&&3==a.g.g},aAa=function(a,b){(a.D.loungeIdToken=b)||a.o.stop()},b7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Fg(a)||"";b&&(this.port=":"+b);this.domain=g.Eg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Xa(a,"10.0")&&(this.o=!1))},c7=function(a,b){var c=a.g;
if(g.u(void 0)?0:a.o)c="https://"+a.domain+a.port+a.g;return g.Og(c+b,{})},d7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Da(a.B,d,!0),onError:g.Da(a.A,e),sd:g.Da(a.C,e)};c&&(a.Ob=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.jE(b,a)},eAa=function(){var a=bAa;
cAa();e7.push(a);dAa(e7)},f7=function(a,b){cAa();
var c=e7,d=fAa(a,String(b));g.kb(c)?gAa(d):(dAa(c),(0,g.G)(c,function(a){a(d)}))},cAa=function(){e7||(e7=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",e7,void 0))},gAa=function(a){var b=(g7+1)%50;
g7=b;h7[b]=a;i7||(i7=49==b)},dAa=function(a){var b=h7;
if(b[0]){var c=g7,d=i7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.G)(a,function(a){a(e)})}while(d!=c);
h7=Array(50);g7=-1;i7=!1}},fAa=function(a,b){var c=((0,g.F)()-hAa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},j7=function(a){g.yF.call(this);
this.F=a;this.g=[]},iAa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},jAa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Id)(a.g,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=iAa(a,b[d])||c;return c},kAa=function(a,b){var c=a.g.length;
a.g=(0,g.Id)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},k7=function(a,b,c,d){g.yF.call(this);
this.D=a;this.C=b;this.A=c;this.B=d;this.o=0;this.g=null;this.Aa=window.NaN},m7=function(a){j7.call(this,"LocalScreenService");
this.A=a;this.o=window.NaN;l7(this);this.info("Initializing with "+j6(this.g))},lAa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=c7(a.A,"/pairing/get_lounge_token_batch");
d7(a.A,c,{screen_ids:b.join(",")},(0,g.z)(a.WH,a),(0,g.z)(a.VH,a))}},l7=function(a){var b=cza(hza());
b=(0,g.Id)(b,function(a){return!a.uuid});
return jAa(a,b)},n7=function(a,b){jza((0,g.H)(a.g,aza));
b&&iza()},p7=function(a,b){g.yF.call(this);
this.D=b;var c=g.uG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.jb(c,l)}this.g=d;this.C=a;this.A=this.B=window.NaN;this.o=null;o7("Initialized with "+g.wg(this.g))},mAa=function(a,b,c){var d=c7(a.C,"/pairing/get_screen_availability");
d7(a.C,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},q7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(o7("Updated online screens: "+g.wg(a.g)),a.g=b,a.T("screenChange"));nAa(a)},r7=function(a){(0,window.isNaN)(a.A)||g.WD(a.A);
a.A=g.UD((0,g.z)(a.gu,a),0<a.B&&a.B<(0,g.F)()?2E4:1E4)},o7=function(a){f7("OnlineScreenService",a)},oAa=function(a){var b={};
(0,g.G)(a.D(),function(a){a.token?b[a.token]=a.id:this.Zb("Requesting availability of screen w/o lounge token.")});
return b},nAa=function(a){a=g.Rb(g.Lb(a.g,function(a){return a}));
g.Db(a);a.length?g.tG("yt-remote-online-screen-ids",a.join(","),60):g.vG("yt-remote-online-screen-ids")},s7=function(a){j7.call(this,"ScreenService");
this.D=a;this.o=this.A=null;this.B=[];this.C={};pAa(this)},rAa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var k=a.fe();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=t7(a,k);mAa(a.o,l,function(a){e(a?l:null)})}else c?qAa(a,c,(0,g.z)(function(a){var f=t7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));mAa(this.o,f,function(a){e(a?f:null)})},a),f):e(null)},sAa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},qAa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ob:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.jE(c7(a.D,"/pairing/get_lounge_token_batch"),e)},tAa=function(a){a.g=a.A.fe();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.g))},pAa=function(a){u7(a);
a.A=new m7(a.D);a.A.subscribe("screenChange",(0,g.z)(a.iI,a));tAa(a);a.B=cza(g.uG("yt-remote-automatic-screen-cache")||[]);u7(a);a.info("Initializing automatic screens: "+j6(a.B));a.o=new p7(a.D,(0,g.z)(a.fe,a,!0));a.o.subscribe("screenChange",(0,g.z)(function(){this.T("onlineScreenChange")},a))},t7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.tG("yt-remote-automatic-screen-cache",(0,g.H)(a.B,aza)));u7(a);a.C[b.uuid]=b.id;g.tG("yt-remote-device-id-map",a.C,31536E3);return b},u7=function(a){a.C=g.uG("yt-remote-device-id-map")||{}},v7=function(a,b,c){g.yF.call(this);
this.N=c;this.I=a;this.o=b;this.A=null},w7=function(a,b){f7(a.N,b)},x7=function(a,b){v7.call(this,a,b,"CastSession");
this.g=null;this.B=0;this.D=(0,g.z)(this.iU,this);this.C=(0,g.z)(this.jS,this);this.B=g.UD((0,g.z)(function(){uAa(this,null)},this),12E4)},vAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.wg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){w7(this,"Failed to send message: getMdxSessionStatus.")},a)):w7(a,"Sending yt message without session: "+g.wg(b))},uAa=function(a,b){g.WD(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.z)(a.Ho,a),d=(0,g.z)(a.ke,a);a.Kx(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},y7=function(a,b,c){v7.call(this,a,b,"DialSession");
this.B=this.G=null;this.J="";this.O=c;this.C=null;this.F=g.y;this.D=window.NaN;this.L=(0,g.z)(this.lU,this);this.g=g.y},wAa=function(a){a.g=a.I.BD(a.J,a.o.label,a.o.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Ho(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ke(a)},a))},xAa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.O;if(a.C){var c=a.C.currentTime||0;b.v=a.C.videoId;b.t=c}lza()&&(b.env_useStageMdx=1);return g.Mg(b)},z7=function(a,b){v7.call(this,a,b,"ManualSession");
this.g=g.UD((0,g.z)(this.Cj,this,null),150)},A7=function(a,b,c,d){g.yF.call(this);
this.o=a;this.F=b||"233637DE";this.D=c||"cl";this.G=d||!1;this.g=null;this.C=!1;this.A=[];this.B=(0,g.z)(this.PQ,this)},yAa=function(a,b){return b?g.eb(a.A,function(a){return h6(b,a.label)},a):null},B7=function(a){f7("Controller",a)},bAa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},C7=function(a){return a.C||!!a.A.length||!!a.g},D7=function(a,b,c){b!=a.g&&(g.Ve(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.o):a.T("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.z)(a.BB,a,b)),b.A?a.T("yt-remote-cast2-session-change",b.A):c&&a.g.Cj(null)):a.T("yt-remote-cast2-session-change",null))},zAa=function(a){var b=a.o.AD(),c=a.g&&a.g.o;
a=(0,g.H)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=yAa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},EAa=function(a,b,c,d,e,f,k){AAa()?BAa(b,e,f,k)&&(F7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?CAa(a,c):(window.__onGCastApiAvailable=function(b,d){b?CAa(a,c):(G7("Failed to load cast API: "+d),H7(!1),F7(!1),g.vG("yt-remote-cast-available"),g.vG("yt-remote-cast-receiver"),DAa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):oza():wza())):E7("Cannot initialize because not running Chrome")},DAa=function(){E7("dispose");
var a=I7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);FAa(!1);g.MF(J7);J7.length=0},K7=function(){return!!g.uG("yt-remote-cast-installed")},GAa=function(){var a=g.uG("yt-remote-cast-receiver");
return a?a.friendlyName:null},HAa=function(){E7("clearCurrentReceiver");
g.vG("yt-remote-cast-receiver")},IAa=function(){return K7()?I7()?I7().getCastSession():(G7("getCastSelector: Cast is not initialized."),null):(G7("getCastSelector: Cast API is not installed!"),null)},M7=function(){K7()?I7()?L7()?(E7("Requesting cast selector."),I7().requestSession()):(E7("Wait for cast API to be ready to request the session."),J7.push(g.LF("yt-remote-cast2-api-ready",M7))):G7("requestCastSelector: Cast is not initialized."):G7("requestCastSelector: Cast API is not installed!")},N7=
function(a,b){L7()?I7().setConnectedScreenStatus(a,b):G7("setConnectedScreenStatus called before ready.")},AAa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.hJ||a},JAa=function(a,b){I7().init(a,b)},BAa=function(a,b,c,d){var e=!1;
I7()||(a=new A7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.tG("yt-remote-cast-available",a);g.PF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){E7("onReceiverSelected: "+a.friendlyName);
g.tG("yt-remote-cast-receiver",a);g.PF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){E7("onReceiverResumed: "+a.friendlyName);
g.tG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){E7("onSessionChange: "+i6(a));
a||g.vG("yt-remote-cast-receiver");g.PF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
E7("cloudview.createSingleton_: "+e);return e},I7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},CAa=function(a,b){H7(!0);
F7(!1);JAa(a,function(a){a?(FAa(!0),g.OF("yt-remote-cast2-api-ready")):(G7("Failed to initialize cast API."),H7(!1),g.vG("yt-remote-cast-available"),g.vG("yt-remote-cast-receiver"),DAa());b(a)})},E7=function(a){f7("cloudview",a)},G7=function(a){f7("cloudview",a)},H7=function(a){E7("setCastInstalled_ "+a);
g.tG("yt-remote-cast-installed",a)},L7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},FAa=function(a){E7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},F7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},O7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Lf=!1;this.J=this.I=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},P7=function(a){a.audioTrackId=null;
a.o=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.F)();a.C=0;a.A=0;a.I=0;a.J=0;a.B=window.NaN;a.D=!1},Q7=function(a){return a.jb()?((0,g.F)()-a.F)/1E3:0},R7=function(a,b){a.G=b;
a.F=(0,g.F)()},S7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},T7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&P7(a)},U7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.I;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},W7=function(a,b){g.yF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.iC;this.A=this.o=null;this.I=(0,g.z)(this.tO,this);this.F=(0,g.z)(this.Dl,this);this.G=(0,g.z)(this.sO,this);this.J=(0,g.z)(this.GO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.cv,this),KAa(this))):c=3;0!=c&&(b?this.cv(c):g.UD((0,g.z)(function(){this.cv(c)},this),0));
var d=IAa();d&&V7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},X7=function(a){return new O7(a.B.getPlayerContextData())},KAa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Da(this.LQ,a),this))},a)},LAa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y7=function(a,b){50>a.C.Jc()&&g.kC(a.C,b)},$7=function(a,b,c){var d=X7(a);
R7(d,c);-1E3!=d.g&&(d.g=b);Z7(a,d)},a8=function(a,b,c){a.B.sendMessage(b,c)},Z7=function(a,b){LAa(a);
a.B.setPlayerContextData(U7(b));KAa(a)},V7=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.Dl(null));
a.A=b;a.A&&(f7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.Dl(a.A.media[0]))},MAa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=X7(a);b.contentId!=d.videoId&&f7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;R7(d,a.o.getEstimatedTime());Z7(a,d)}else f7("CP","No cast media video. Ignoring state update.")},b8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),a8(this,b,c))},a)},c8=function(a,b,c){g.yF.call(this);
this.C=window.NaN;this.O=!1;this.J=this.I=this.L=this.N=window.NaN;this.R=[];this.B=this.F=this.A=this.bb=this.g=null;this.na=a;this.R.push(g.jF(window,"beforeunload",(0,g.z)(this.NH,this)));this.o=[];this.bb=new O7;this.Z=b.id;this.g=NAa(this,c);this.g.subscribe("handlerOpened",this.xO,this);this.g.subscribe("handlerClosed",this.uO,this);this.g.subscribe("handlerError",this.vO,this);this.g.subscribe("handlerMessage",this.wO,this);aAa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.zG()&&g.tG("yt-remote-session-video-id",a)},this)},d8=function(a){f7("conn",a)},NAa=function(a,b){return new $6(c7(a.na,"/bc"),b)},e8=function(a,b){a.T("proxyStateChange",b)},OAa=function(a){a.C=g.UD((0,g.z)(function(){d8("Connecting timeout");
this.D(1)},a),2E4)},f8=function(a){g.WD(a.C);
a.C=window.NaN},g8=function(a){g.WD(a.N);
a.N=window.NaN},PAa=function(a){h8(a);
a.L=g.UD((0,g.z)(function(){i8(this,"getNowPlaying")},a),2E4)},h8=function(a){g.WD(a.L);
a.L=window.NaN},RAa=function(a,b){b&&(f8(a),g8(a));
b==(a7(a.g)&&(0,window.isNaN)(a.C))?b&&(e8(a,1),i8(a,"getSubtitlesTrack")):b?(a.X()&&a.bb.reset(),e8(a,1),i8(a,"getNowPlaying"),QAa(a)):a.D(1)},SAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Xb(b.params)?a.bb.o=null:a.bb.o=b.params,a.T("remotePlayerChange"))},TAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;T7(a.bb,c,d);a.T("remoteQueueChange")},VAa=function(a,b){b.params=b.params||{};
TAa(a,b);UAa(a,b);a.T("autoplayDismissed")},UAa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
R7(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.I=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:e;1==a.bb.g?PAa(a):h8(a);
a.T("remotePlayerChange")},WAa=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);R7(a.bb,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},XAa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.T("remotePlayerChange")},YAa=function(a,b){a.F=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},ZAa=function(a,b){var c="true"==b.params.hasNext;
a.bb.Lf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.T("previousNextChange")},QAa=function(a){g.WD(a.J);
a.J=g.UD((0,g.z)(a.D,a,1),864E5)},i8=function(a,b,c){c?d8("Sending: action="+b+", params="+g.wg(c)):d8("Sending: action="+b);
a.g.sendMessage(b,c)},j8=function(a){j7.call(this,"ScreenServiceProxy");
this.dd=a;this.o=[];this.o.push(this.dd.$_s("screenChange",(0,g.z)(this.gU,this)));this.o.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.rQ,this)))},dBa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.OD("MDX_CONFIG")||b;g.rG&&Uya();q6();k8||(k8=new b7(b?b.loungeApiHost:void 0),lza()&&(k8.g="/api/loungedev"));l8||(l8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",l8,void 0));$Aa();var c=m8();if(!c){var d=new s7(k8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=m8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);EAa(a,d,function(a){a?n8()&&N7(n8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.PF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),o8("Initializing: "+g.wg(b)),p8.push(g.LF("yt-remote-cast2-availability-change",function(){g.PF("yt-remote-receiver-availability-change")})),p8.push(g.LF("yt-remote-cast2-receiver-selected",function(){q8(null);
g.PF("yt-remote-auto-connect","cast-selector-receiver")})),p8.push(g.LF("yt-remote-cast2-receiver-resumed",function(){g.PF("yt-remote-receiver-resumed","cast-selector-receiver")})),p8.push(g.LF("yt-remote-cast2-session-change",aBa)),p8.push(g.LF("yt-remote-connection-change",function(a){a?N7(n8(),"YouTube TV"):r8()||(N7(null,null),HAa())})),a=O8(),b.isAuto&&(a.id+="#dial"),g.CE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),o8(" -- with channel params: "+
g.wg(a)),bBa(a),c.start(),n8()||cBa())},fBa=function(){var a=eBa();
K7()&&g.uG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},eBa=function(){var a=m8().dd.$_gos();
var b=P8();b&&X8()&&(l6(a,b)||a.push(b));return dza(a)},$8=function(){var a=gBa();
!a&&K7()&&GAa()&&(a={key:"cast-selector-receiver",name:GAa()});return a},gBa=function(){var a=eBa(),b=P8();
b||(b=r8());return g.eb(a,function(a){return b&&h6(b,a.key)?!0:!1})},P8=function(){var a=n8();
if(!a)return null;var b=m8().fe();return m6(b,a)},aBa=function(a){o8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=P8();b&&b.id==a.id?N7(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else X8()&&a9()},a9=function(){L7()?I7().stopSession():G7("stopSession called before API ready.");
var a=X8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=X8();
return!!a&&3!=a.getProxyState()},o8=function(a){f7("remote",a)},m8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new j8(a):null}return e9},n8=function(){return g.x("yt.mdx.remote.currentScreenId_")},hBa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},iBa=function(){return g.x("yt.mdx.remote.connectData_")},q8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},X8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=X8();
q8(null);a||hBa("");g.ua("yt.mdx.remote.connection_",a,void 0);l8&&((0,g.G)(l8,function(b){b(a)}),l8.length=0);
b&&!a?g.PF("yt-remote-connection-change",!1):!b&&a&&g.PF("yt-remote-connection-change",!0)},r8=function(){var a=g.zG();
if(!a)return null;var b=m8().fe();return m6(b,a)},b9=function(a,b){P8()&&P8();
hBa(a.id);var c=new c8(k8,a,O8());c.connect(b,iBa());c.subscribe("beforeDisconnect",function(a){g.PF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){X8()&&c9(null)});
c9(c)},cBa=function(){var a=r8();
a?(o8("Resume connection to: "+i6(a)),b9(a,0)):(r6(),HAa(),o8("Skipping connecting because no session screen found."))},$Aa=function(){var a=O8();
if(g.Xb(a)){a=p6();var b=g.uG("yt-remote-session-name")||"",c=g.uG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},O8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},bBa=function(a){a?(g.tG("yt-remote-session-app",a.app),g.tG("yt-remote-session-name",a.name)):(g.vG("yt-remote-session-app"),g.vG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.L.call(this);
this.G=a;this.o=b;this.A=new g.vF(this);g.M(this,this.A);this.A.P(b,"onCaptionsTrackListChanged",this.KP);this.A.P(b,"captionschanged",this.rO);this.A.P(b,"captionssettingschanged",this.RC);this.A.P(b,"videoplayerreset",this.Io);this.A.P(b,"mdxautoplaycancel",this.SG);this.R=this.A.P(b,"onVolumeChange",this.lB);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.yB,this);c.subscribe("remotePlayerChange",this.Fl,this);c.subscribe("remoteQueueChange",this.Io,this);c.subscribe("autoplayUpNext",this.XA,
this);c.subscribe("previousNextChange",this.vB,this);c.subscribe("nowAutoplaying",this.nB,this);c.subscribe("autoplayDismissed",this.WA,this);this.suggestion=null;this.I=new g.hO(64);this.B=new g.Wt(this.NC,500,this);g.M(this,this.B);this.C=new g.Wt(this.OC,1E3,this);g.M(this,this.C);this.L=new z6(this.GT,0,this);g.M(this,this.L);this.D={};this.N=new g.Wt(this.pD,1E3,this);g.M(this,this.N);this.J=new g.Ok(this.cL,1E3,this);g.M(this,this.J);this.O=g.y;this.RC();this.Io();this.Fl()},g9=function(a,b){var c=
a.G,d=a.o.fa().lengthSeconds;
c.I=b||0;c.g.T("progresssync",b,d)},jBa=function(a){g9(a,0);
a.B.stop();h9(a,new g.hO(64))},j9=function(a,b){if(i9(a)&&!a.F){var c=null;
b&&(c={style:a.o.yi()},g.dc(c,b));a.g.FC(a.o.fa(1).videoId,c);a.D=X7(a.g).o}},k9=function(a,b){var c=a.o.Xf();
if(c){var d=c.ce();var e=c.listId.toString()}var f=a.o.fa(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.xj;var m=X7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};T7(m,k,l);g.u(b)&&(R7(m,b),q.currentTime=b);g.u(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);a8(c,"setPlaylist",q);e||Z7(c,m);h9(a,new g.hO(1))},kBa=function(a,b){if(b){var c=a.o.xc("captions","tracklist",{Iy:1});
c&&c.length?(a.o.Fd("captions","track",b),a.F=!1):(a.o.ul("captions"),a.F=!0)}else a.o.Fd("captions","track",{})},i9=function(a){return X7(a.g).videoId==a.o.fa(1).videoId},h9=function(a,b){a.C.stop();
var c=a.I;if(!g.oO(c,b)){var d=g.V(b,2);d!=g.V(a.I,2)&&g.lU(a.o,d);a.I=b;lBa(a.G,c,b)}},l9=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.hV()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.GV(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);mBa(this,g.iU(a))},mBa=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},m9=function(a,b){g.e_.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.G={};this.P(a,"onMdxReceiversChange",this.J);this.P(a,"presentingplayerstatechange",this.J);this.J()},n9=function(a){g.IU.call(this,a);
this.A={key:k6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.hO(64);this.I=0;if(!g.PL(g.X(this.g))){a=this.g;var b=g.bU(a).I;b&&(b=b.A&&b.A.g)&&(b=new m9(a,b),g.M(this,b));b=new l9(a);g.M(this,b);g.CU(a,b.element,4)}},lBa=function(a,b,c){a.F=c;
a.g.T("presentingplayerstatechange",new g.uO(c,b))},o9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)a9();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.fa(1),e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.fc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xj,index:Math.max(a.g.Qz(),0),currentTime:0==f?void 0:f}}else c=null;o8("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(q8(c||null),L7()?I7().setLaunchParams(c||null):G7("setLaunchParams called before ready.")):!c&&
d9()&&n8()==b.key?g.PF("yt-remote-connection-change",!0):(a9(),q8(c||null),c=m8().fe(),(c=m6(c,b.key))&&b9(c,1))}},Cza={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},J6={"'":"\\'"},nBa={},$ya={PV:"atp",o0:"ska",E_:"que",SZ:"mus",k0:"sus"};
f6.prototype.ln=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.A=this.A;a.o=this.o;a.g=this.g};
var s6,o6="",tza=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",uza=t6("loadCastFramework")||t6("loadCastApplicationFramework"),v6=["boadgeojelhgndaghljhdicfkmllpafd","dliochdbjfkdbacpmhlcpmleaejidimm","enhhojjnijigcajfphajepfemndkmdlo","fmfcbgogabcbclcofgocippekhfcmgfj"],oBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","fjhoaacokmgbjemoflkofnenfaiekifl"],sza=50<=pza()?oBa.concat(v6):v6.concat(oBa);g.A(z6,g.L);g.h=z6.prototype;g.h.JH=function(a){this.B=arguments;this.g=!1;this.Aa?this.A=(0,g.F)()+this.qc:this.Aa=g.qg(this.C,this.qc)};
g.h.stop=function(){this.Aa&&(g.rg(this.Aa),this.Aa=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.W=function(){this.stop();z6.Y.W.call(this)};
g.h.KH=function(){this.A?(this.Aa=g.qg(this.C,this.A-(0,g.F)()),this.A=null):(this.Aa=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};A6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
A6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=B6.prototype;g.h.hi=null;g.h.vf=!1;g.h.pk=null;g.h.Wu=null;g.h.Tj=null;g.h.nj=null;g.h.mh=null;g.h.Fh=null;g.h.Gi=null;g.h.Nc=null;g.h.Sl=0;g.h.wf=null;g.h.zp=null;g.h.nh=null;g.h.Uk=-1;g.h.oC=!0;g.h.Rh=!1;g.h.xr=0;g.h.Ro=null;var Aza={},E6={};g.h=B6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.DS=function(a){a=a.target;var b=this.Ro;b&&3==g.qx(a)?b.lj():this.vD(a)};
g.h.vD=function(a){try{if(a==this.Nc)a:{var b=g.qx(this.Nc),c=this.Nc.o,d=this.Nc.getStatus();if(g.ud&&!g.qc(10)||g.wd&&!g.pc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ze&&!g.ux(this.Nc))break a;this.Rh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));L6(this);var e=this.Nc.getStatus();this.Uk=e;var f=g.ux(this.Nc);(this.vf=200==e)?(4==b&&H6(this),this.D?(Bza(this,b,f),g.Ze&&this.vf&&3==b&&(this.B.U(this.o,"tick",this.vS),this.o.start())):G6(this,f),this.vf&&!this.Rh&&(4==b?this.g.Go(this):
(this.vf=!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.nh=3,F6(13)):(this.nh=0,F6(14)),H6(this),I6(this))}}catch(k){this.Nc&&g.ux(this.Nc)}finally{}};
g.h.vS=function(){var a=g.qx(this.Nc),b=g.ux(this.Nc);this.Sl<b.length&&(L6(this),Bza(this,a,b),this.vf&&4!=a&&D6(this))};
g.h.IR=function(a){K6((0,g.z)(this.HR,this,a),0)};
g.h.HR=function(a){this.Rh||(L6(this),G6(this,a),D6(this))};
g.h.GB=function(a){K6((0,g.z)(this.GR,this,a),0)};
g.h.GR=function(a){this.Rh||(H6(this),this.vf=a,this.g.Go(this),this.g.rf(4))};
g.h.cancel=function(){this.Rh=!0;H6(this)};
g.h.ZR=function(){this.pk=null;var a=(0,g.F)();0<=a-this.Wu?(2!=this.nj&&this.g.rf(3),H6(this),this.nh=2,F6(18),I6(this)):Eza(this,this.Wu-a)};g.h=Hza.prototype;g.h.ur=null;g.h.oe=null;g.h.To=!1;g.h.Sx=null;g.h.zn=null;g.h.vr=null;g.h.wr=null;g.h.Ke=null;g.h.Bg=-1;g.h.Tk=null;g.h.tk=null;g.h.connect=function(a){this.wr=a;a=N6(this.g,null,this.wr);F6(3);this.Sx=(0,g.F)();var b=this.g.G;null!=b?(this.Tk=b[0],(this.tk=b[1])?(this.Ke=1,Iza(this)):(this.Ke=2,P6(this))):(e6(a,"MODE","init"),this.oe=new B6(this,void 0,void 0,void 0),this.oe.hi=this.ur,C6(this.oe,a,!1,null,!0),this.Ke=0)};
g.h.TG=function(a){if(a)this.Ke=2,P6(this);else{F6(4);var b=this.g;b.ff=b.ah.Bg;W6(b,9)}a&&this.rf(2)};
g.h.Oq=function(a){return this.g.Oq(a)};
g.h.abort=function(){this.oe&&(this.oe.cancel(),this.oe=null);this.Bg=-1};
g.h.Rx=function(){return!1};
g.h.zB=function(a,b){this.Bg=a.Uk;if(0==this.Ke)if(b){try{var c=this.o.parse(b)}catch(d){c=this.g;c.ff=this.Bg;W6(c,2);return}this.Tk=c[0];this.tk=c[1]}else c=this.g,c.ff=this.Bg,W6(c,2);else if(2==this.Ke)if(this.To)F6(7),this.vr=(0,g.F)();else if("11111"==b){if(F6(6),this.To=!0,this.zn=(0,g.F)(),c=this.zn-this.Sx,!g.ud||g.qc(10)||500>c)this.Bg=200,this.oe.cancel(),F6(12),O6(this.g,this,!0)}else F6(8),this.zn=this.vr=(0,g.F)(),this.To=!1};
g.h.Go=function(){this.Bg=this.oe.Uk;if(this.oe.vf)0==this.Ke?this.tk?(this.Ke=1,Iza(this)):(this.Ke=2,P6(this)):2==this.Ke&&((!g.ud||g.qc(10)?!this.To:200>this.vr-this.zn)?(F6(11),O6(this.g,this,!1)):(F6(12),O6(this.g,this,!0)));else{0==this.Ke?F6(9):2==this.Ke&&F6(10);var a=this.g;a.ff=this.Bg;W6(a,2)}};
g.h.Ml=function(){return this.g.Ml()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=Q6.prototype;g.h.Gk=null;g.h.Nd=null;g.h.kc=null;g.h.tr=null;g.h.Cn=null;g.h.jw=null;g.h.Rn=null;g.h.Bl=0;g.h.KN=0;g.h.pd=null;g.h.dh=null;g.h.vg=null;g.h.Vh=null;g.h.ah=null;g.h.yp=null;g.h.Bj=-1;g.h.Ry=-1;g.h.ff=-1;g.h.fj=0;g.h.Wi=0;g.h.Th=8;var X6=new g.yf;g.A(Kza,g.Xe);g.A(Lza,g.Xe);g.A(Mza,g.Xe);g.h=Q6.prototype;g.h.connect=function(a,b,c,d,e){F6(0);this.tr=b;this.Gk=c||{};d&&g.u(e)&&(this.Gk.OSID=d,this.Gk.OAID=e);this.D?(K6((0,g.z)(this.Jw,this,a),100),Qza(this)):this.Jw(a)};
g.h.Jw=function(a){this.ah=new Hza(this);this.ah.ur=null;this.ah.o=this.C;this.ah.connect(a)};
g.h.Rx=function(){return 0==this.g};
g.h.EB=function(a){this.dh=null;Tza(this,a)};
g.h.DB=function(){this.vg=null;this.kc=new B6(this,this.A,"rpc",this.F);this.kc.hi=null;this.kc.xr=0;var a=this.jw.clone();g.Bm(a,"RID","rpc");g.Bm(a,"SID",this.A);g.Bm(a,"CI",this.yp?"0":"1");g.Bm(a,"AID",this.Bj);R6(this,a);if(!g.ud||g.qc(10))g.Bm(a,"TYPE","xmlhttp"),C6(this.kc,a,!0,this.Rn,!1);else{g.Bm(a,"TYPE","html");var b=this.kc,c=!!this.Rn;b.nj=3;b.mh=d6(a.clone());Dza(b,c)}};
g.h.zB=function(a,b){if(0!=this.g&&(this.kc==a||this.Nd==a))if(this.ff=a.Uk,this.Nd==a&&3==this.g)if(7<this.Th){try{var c=this.C.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.vg){if(this.kc)if(this.kc.Tj+3E3<this.Nd.Tj)T6(this),this.kc.cancel(),this.kc=null;else break a;V6(this);F6(19)}}else this.Ry=c[1],0<this.Ry-this.Bj&&37500>c[2]&&this.yp&&0==this.Wi&&!this.Vh&&(this.Vh=K6((0,g.z)(this.mO,this),6E3));else W6(this,11)}else b!=nBa.SW.g&&W6(this,11);else if(this.kc==a&&
T6(this),!g.C(b)){c=this.C.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Bj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.A=e[1],this.Rn=e[2],e=e[3],null!=e?this.Th=e:this.Th=6,this.g=3,this.pd&&this.pd.yw(),this.jw=N6(this,this.Ml()?this.Rn:null,this.tr),Uza(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.pd&&this.pd.xw(e),this.Wi=0)}}};
g.h.mO=function(){null!=this.Vh&&(this.Vh=null,this.kc.cancel(),this.kc=null,V6(this),F6(20))};
g.h.Go=function(a){if(this.kc==a){T6(this);this.kc=null;var b=2}else if(this.Nd==a)this.Nd=null,b=1;else return;this.ff=a.Uk;if(0!=this.g)if(a.vf)1==b?(b=(0,g.F)()-a.Tj,X6.dispatchEvent(new Lza(X6,a.Gi?a.Gi.length:0,b,this.fj)),S6(this),this.B.length=0):Uza(this);else{var c=a.nh,d;if(!(d=3==c||7==c||0==c&&0<this.ff)){if(d=1==b)this.Nd||this.dh||1==this.g||2<=this.fj?d=!1:(this.dh=K6((0,g.z)(this.EB,this,a),Vza(this,this.fj)),this.fj++,d=!0);d=!(d||2==b&&V6(this))}if(d)switch(c){case 1:W6(this,5);
break;case 4:W6(this,10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.rH=function(a){if(!g.jb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.xT=function(a){a?F6(2):(F6(1),Wza(this,8))};
g.h.Oq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.kx;a.G=!1;return a};
g.h.isActive=function(){return!!this.pd&&this.pd.isActive(this)};
g.h.rf=function(a){X6.dispatchEvent(new Mza(X6,a))};
g.h.Ml=function(){return!(!g.ud||g.qc(10))};
g.h=Xza.prototype;g.h.yw=function(){};
g.h.xw=function(){};
g.h.ww=function(){};
g.h.Dq=function(){};
g.h.yx=function(){return{}};
g.h.isActive=function(){return!0};g.A(Z6,g.L);Z6.prototype.A=function(){500<this.qc&&24E4>2*this.qc&&(this.qc*=2);this.B();this.o&&this.start()};
Z6.prototype.start=function(){g.Xt(this.g,this.qc);this.o=(0,g.F)()+this.qc};
Z6.prototype.stop=function(){this.g.stop();this.o=0};
Z6.prototype.isActive=function(){return this.g.isActive()};g.A($6,Xza);g.h=$6.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Hd=function(a){return this.A.Hd(a)};
g.h.T=function(a,b){return this.A.T.apply(this.A,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.Ve(this.A),$za(this),g.Ve(this.o),this.o=null)};
g.h.ia=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.o.stop();this.C=a||null;this.B=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Q6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.pd=null);d.pd=this;this.g=d;e?this.g.connect(a,b,this.D,e.A,e.Bj):c?this.g.connect(a,b,this.D,c.sessionId,c.arrayId):this.g.connect(a,b,this.D)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.o.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):a7(this)&&Rza(this.g,c)};
g.h.yw=function(){Y6(this.o);this.C=null;this.B=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Rza(this.g,a[b])}this.T("handlerOpened")};
g.h.ww=function(a){var b=2==a&&401==this.g.ff;if(4!=a&&!b){if(6==a||410==this.g.ff)b=this.o,b.g.stop(),b.qc=500;this.o.start()}this.T("handlerError",a)};
g.h.Dq=function(a){if(!this.o.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.yx=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.G&&(a.ui=""+this.G);this.C&&g.dc(a,this.C);return a};
g.h.xw=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(Y6(this.o),this.o.start(),Pza(this.g)):this.T("handlerMessage",new Yza(a[0],a[1]))};
g.h.cU=function(){this.o.isActive();var a=this.g,b=0;a.kc&&b++;a.Nd&&b++;0!=b?this.o.start():this.connect(this.C,this.B)};b7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
b7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
b7.prototype.C=function(a){a(Error("request timed out"))};var hAa=(0,g.F)(),e7=null,h7=Array(50),g7=-1,i7=!1;g.A(j7,g.yF);j7.prototype.fe=function(){return this.g};
j7.prototype.contains=function(a){return!!l6(this.g,a)};
j7.prototype.get=function(a){return a?m6(this.g,a):null};
j7.prototype.info=function(a){f7(this.F,a)};g.A(k7,g.yF);var pBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=k7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.zD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.WD(this.Aa),this.Aa=window.NaN)};
g.h.W=function(){this.stop();k7.Y.W.call(this)};
g.h.zD=function(){this.Aa=window.NaN;this.g=g.jE(c7(this.D,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:this.C},timeout:5E3,Hb:(0,g.z)(this.eU,this),onError:(0,g.z)(this.dU,this),sd:(0,g.z)(this.fU,this)})};
g.h.eU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.T("pairingComplete",new g6(c))};
g.h.dU=function(a){this.g=null;a.status&&404==a.status?this.o>=pBa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=pBa[this.o],this.Aa=g.UD((0,g.z)(this.zD,this),a),this.o++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.fU=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.A(m7,j7);g.h=m7.prototype;g.h.start=function(){l7(this)&&this.T("screenChange");!g.uG("yt-remote-lounge-token-expiration")&&lAa(this);g.WD(this.o);this.o=g.UD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){l7(this);iAa(this,a);n7(this,!1);this.T("screenChange");b(a);a.token||lAa(this)};
g.h.remove=function(a,b){var c=l7(this);kAa(this,a)&&(n7(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.up=function(a,b,c,d){var e=l7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,n7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.W=function(){g.WD(this.o);m7.Y.W.call(this)};
g.h.WH=function(a){l7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}n7(this,!b);b&&f7(this.F,"Missed "+b+" lounge tokens.")};
g.h.VH=function(a){f7(this.F,"Requesting lounge tokens failed: "+a)};g.A(p7,g.yF);g.h=p7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.uG("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.F)()-144E5<a?0:a)?r7(this):(this.B=(0,g.F)()+3E5,g.tG("yt-remote-fast-check-period",this.B),this.gu())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){o7("Updating availability on schedule.");var a=this.D(),b=g.Lb(this.g,function(b,d){return b&&!!m6(a,d)},this);
q7(this,b)};
g.h.W=function(){g.WD(this.A);this.A=window.NaN;this.o&&(this.o.abort(),this.o=null);p7.Y.W.call(this)};
g.h.gu=function(){g.WD(this.A);this.A=window.NaN;this.o&&this.o.abort();var a=oAa(this);if(g.Pb(a)){var b=c7(this.C,"/pairing/get_screen_availability");this.o=d7(this.C,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.iR,this,a),(0,g.z)(this.hR,this))}else q7(this,{}),r7(this)};
g.h.iR=function(a,b){this.o=null;var c=g.Rb(oAa(this));if(g.Eb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;q7(this,d);r7(this)}else this.Zb("Changing Screen set during request."),this.gu()};
g.h.hR=function(a){this.Zb("Screen availability failed: "+a);this.o=null;r7(this)};
g.h.Zb=function(a){f7("OnlineScreenService",a)};g.A(s7,j7);g.h=s7.prototype;g.h.start=function(){this.A.start();this.o.start();this.g.length&&(this.T("screenChange"),this.o.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.A.add(a,b,c)};
g.h.remove=function(a,b,c){this.A.remove(a,b,c);this.o.update()};
g.h.up=function(a,b,c,d){this.A.contains(a)?this.A.up(a,b,c,d):(a="Updating name of unknown screen: "+a.name,f7(this.F,a),d(Error(a)))};
g.h.fe=function(a){return a?this.g:g.tb(this.g,(0,g.Id)(this.B,function(a){return!this.contains(a)},this))};
g.h.AD=function(){return(0,g.Id)(this.fe(!0),function(a){return!!this.o.g[a.id]},this)};
g.h.BD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new k7(this.D,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ve(f);d(t7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ve(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.hU=function(a,b,c,d){g.jE(c7(this.D,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new g6(d.screen||{});if(!e.name||sAa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);sAa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(t7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
sd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Ve(this.A);g.Ve(this.o);s7.Y.W.call(this)};
g.h.iI=function(){tAa(this);this.T("screenChange");this.o.update()};
s7.prototype.dispose=s7.prototype.dispose;g.A(v7,g.yF);g.h=v7.prototype;g.h.Ho=function(a){this.A=a;this.T("sessionScreen",this.A)};
g.h.ke=function(a){this.ia()||(a&&w7(this,""+a),this.A=null,this.T("sessionScreen",null))};
g.h.info=function(a){f7(this.N,a)};
g.h.DD=function(){return null};
g.h.nu=function(a){var b=this.o;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){w7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.nu("");v7.Y.W.call(this)};g.A(x7,v7);g.h=x7.prototype;g.h.mu=function(a){if(this.g){if(this.g==a)return;w7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.D);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.g=a;this.g.addUpdateListener(this.D);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);vAa(this)};
g.h.Cj=function(a){this.info("launchWithParams no-op for Cast: "+g.wg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ke()},this),(0,g.z)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.nu=g.y;g.h.W=function(){this.info("disposeInternal");g.WD(this.B);this.B=0;this.g&&(this.g.removeUpdateListener(this.D),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.g=null;x7.Y.W.call(this)};
g.h.jS=function(a,b){if(!this.ia())if(b){var c=g.ex(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.wg(c));switch(d){case "mdxSessionStatus":uAa(this,c.screenId);break;default:w7(this,"Unknown youtube message: "+d)}}else w7(this,"Unable to parse message.")}else w7(this,"No data in message.")};
g.h.Kx=function(a,b,c,d){rAa(this.I,this.o.label,a,this.o.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(w7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.UD((0,g.z)(this.Kx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.DD=function(){return this.g};
g.h.iU=function(a){this.ia()||a||(w7(this,"Cast session died."),this.ke())};g.A(y7,v7);g.h=y7.prototype;g.h.mu=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.Cj=function(a){this.C=a;this.F()};
g.h.stop=function(){this.g();this.g=g.y;g.WD(this.D);this.B?this.B.stop((0,g.z)(this.ke,this,null),(0,g.z)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.W=function(){this.g();this.g=g.y;g.WD(this.D);this.B&&this.B.removeUpdateListener(this.L);this.B=null;y7.Y.W.call(this)};
g.h.lU=function(a){this.ia()||a||(w7(this,"DIAL session died."),this.g(),this.g=g.y,this.ke())};
g.h.hs=function(a){this.J=k6();if(this.C){var b=new window.chrome.cast.DialLaunchResponse(!0,xAa(this));a(b);wAa(this)}else this.F=(0,g.z)(function(){g.WD(this.D);this.F=g.y;this.D=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,xAa(this));a(b);wAa(this)},this),this.D=g.UD((0,g.z)(function(){this.F()},this),100)};
g.h.zJ=function(a,b,c){rAa(this.I,this.G.receiver.label,a,this.o.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Ho(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.hs(b,c)},this),(0,g.z)(function(a){w7(this,"Failed to get DIAL screen: "+a);
this.hs(b,c)},this))};g.A(z7,v7);z7.prototype.stop=function(){this.ke()};
z7.prototype.mu=g.y;z7.prototype.Cj=function(){g.WD(this.g);this.g=window.NaN;var a=m6(this.I.fe(),this.o.label);a?this.Ho(a):this.ke(Error("No such screen"))};
z7.prototype.W=function(){g.WD(this.g);this.g=window.NaN;z7.Y.W.call(this)};g.A(A7,g.yF);g.h=A7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.AB,this),(0,g.z)(this.TQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.XO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.B),eAa(),this.o.subscribe("onlineScreenChange",(0,g.z)(this.CD,this)),this.A=zAa(this),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.wg(a))},this)),this.T("yt-remote-cast2-availability-change",C7(this)),b(!0))},this),(0,g.z)(function(a){this.Zb("Failed to initialize API: "+g.wg(a));
b(!1)},this))};
g.h.gT=function(a,b){B7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.A;if(!a||c&&c.id!=a)B7("Unsetting old screen status: "+this.g.o.friendlyName),D7(this,null)}if(a&&b){if(!this.g){c=m6(this.o.fe(),a);if(!c){B7("setConnectedScreenStatus: Unknown screen.");return}var d=yAa(this,c);d||(B7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.A.push(d),
window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.wg(a))},this)));
B7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);D7(this,new z7(this.o,d),!0)}this.g.nu(b)}else B7("setConnectedScreenStatus: no screen.")};
g.h.hT=function(a){this.ia()?this.Zb("Setting connection data on disposed cast v2"):this.g?this.g.Cj(a):this.Zb("Setting connection data without a session")};
g.h.kU=function(){this.ia()?this.Zb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),D7(this,null)):B7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.AB,this),(0,g.z)(this.mR,this))};
g.h.W=function(){this.o.unsubscribe("onlineScreenChange",(0,g.z)(this.CD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.B);g.rb(g.x("yt.mdx.remote.debug.handlers_")||[],bAa);g.Ve(this.g);A7.Y.W.call(this)};
g.h.Zb=function(a){f7("Controller",a)};
g.h.BB=function(a,b){this.g==a&&(b||D7(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.PQ=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),B7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.o.label!=a.label)B7("onReceiverAction_: Stopping active receiver: "+this.g.o.friendlyName),this.g.stop();else{B7("onReceiverAction_: Casting to active receiver.");this.g.A&&this.T("yt-remote-cast2-session-change",this.g.A);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:D7(this,
new z7(this.o,a));break;case window.chrome.cast.ReceiverType.DIAL:D7(this,new y7(this.o,a,this.D));break;case window.chrome.cast.ReceiverType.CAST:D7(this,new x7(this.o,a));break;default:this.Zb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.o.label==a.label?this.g.stop():this.Zb("Stopping receiver w/o session: "+a.friendlyName)}else this.Zb("onReceiverAction_ called without receiver.")};
g.h.XO=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Zb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.o:null;if(!c||c.label!=b.label)return this.Zb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.A)return B7("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.A),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Zb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);D7(this,new y7(this.o,b,this.D))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.zJ,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.hs,b))};
g.h.AB=function(a){if(!this.ia()){B7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)B7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),D7(this,new x7(this.o,b),!0);else{this.Zb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.o,d=m6(this.o.fe(),c.label);
d&&h6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(B7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ve(this.g),this.g=new x7(this.o,b),this.g.subscribe("sessionScreen",(0,g.z)(this.BB,this,this.g)),this.g.Cj(null));this.g.mu(a)}}};
g.h.jU=function(){return this.g?this.g.DD():null};
g.h.mR=function(a){this.ia()||(this.Zb("Failed to estabilish a session: "+g.wg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&D7(this,null))};
g.h.TQ=function(a){B7("Receiver availability updated: "+a);if(!this.ia()){var b=C7(this);this.C=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;C7(this)!=b&&this.T("yt-remote-cast2-availability-change",C7(this))}};
g.h.CD=function(){this.ia()||(this.A=zAa(this),B7("Updating custom receivers: "+g.wg(this.A)),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(){this.Zb("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",C7(this)))};
A7.prototype.setLaunchParams=A7.prototype.hT;A7.prototype.setConnectedScreenStatus=A7.prototype.gT;A7.prototype.stopSession=A7.prototype.kU;A7.prototype.getCastSession=A7.prototype.jU;A7.prototype.requestSession=A7.prototype.requestSession;A7.prototype.init=A7.prototype.init;A7.prototype.dispose=A7.prototype.dispose;var J7=[];O7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";P7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.I=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
O7.prototype.jb=function(){return 1==this.g};
O7.prototype.getDuration=function(){return this.D?this.I+Q7(this):this.I};
O7.prototype.clone=function(){return new O7(U7(this))};g.A(W7,g.yF);g.h=W7.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,b8(this,"play")):a8(this,"play"),$7(this,1,S7(X7(this))),this.T("remotePlayerChange")):Y7(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,b8(this,"pause")):a8(this,"pause"),$7(this,2,S7(X7(this))),this.T("remotePlayerChange")):Y7(this,this.pause)};
g.h.yD=function(a){if(1==this.g){if(this.o){var b=X7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,b8(this,"seekTo",{newTime:a}))}else a8(this,"seekTo",{newTime:a});$7(this,3,a);this.T("remotePlayerChange")}else Y7(this,g.Da(this.yD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,b8(this,"stopVideo")):a8(this,"stopVideo");var a=X7(this);a.index=-1;a.videoId="";P7(a);Z7(this,a);this.T("remotePlayerChange")}else Y7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=X7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){f7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){f7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);a8(this,"setVolume",e)}c.muted=b;c.volume=a;Z7(this,c)}else Y7(this,g.Da(this.setVolume,a,b))};
g.h.FC=function(a,b){if(1==this.g){var c=X7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.dc(d,c.o));a8(this,"setSubtitlesTrack",d);Z7(this,c)}else Y7(this,g.Da(this.FC,a,b))};
g.h.bv=function(a,b){if(1==this.g){a8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Rc.id});var c=X7(this);c.audioTrackId=b.Rc.id;Z7(this,c)}else Y7(this,g.Da(this.bv,a,b))};
g.h.xD=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"previous")}else Y7(this,g.Da(this.xD,a,b))};
g.h.wD=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"next")}else Y7(this,g.Da(this.wD,a,b))};
g.h.Xw=function(){1==this.g?a8(this,"dismissAutoplay"):Y7(this,this.Xw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}W7.Y.dispose.call(this)};
g.h.W=function(){LAa(this);this.B=null;this.C.clear();V7(this,null);W7.Y.W.call(this)};
g.h.cv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.lC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.LQ=function(a,b){this.T(a,b)};
g.h.tO=function(a){if(!a)this.Dl(null),V7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=X7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)f7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,Z7(this,b)}};
g.h.Dl=function(a){f7("CP","Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),MAa(this),this.T("remotePlayerChange")};
g.h.sO=function(a){a?(MAa(this),this.T("remotePlayerChange")):this.Dl(null)};
g.h.GO=function(){var a=IAa();a&&V7(this,a)};
g.h.Zb=function(a){f7("CP",a)};g.A(c8,g.yF);g.h=c8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;R7(this.bb,m);this.B="UNSUPPORTED";d8("Connecting with setPlaylist and params: "+g.wg(l));this.g.connect({method:"setPlaylist",params:g.wg(l)},a,gza())}else d8("Connecting without params"),
this.g.connect({},a,gza());OAa(this)};
g.h.dispose=function(){this.ia()||(this.T("beforeDispose"),e8(this,3));c8.Y.dispose.call(this)};
g.h.W=function(){f8(this);h8(this);g8(this);g.WD(this.I);this.I=window.NaN;g.WD(this.J);this.J=window.NaN;this.A=null;g.kF(this.R);this.R.length=0;this.g.dispose();c8.Y.W.call(this);this.B=this.F=this.o=this.bb=this.g=null};
g.h.NH=function(){this.D(2)};
g.h.xO=function(){d8("Channel opened");this.O&&(this.O=!1,g8(this),this.N=g.UD((0,g.z)(function(){d8("Timing out waiting for a screen.");this.D(1)},this),15E3));
kza(Zza(this.g),this.Z)};
g.h.uO=function(){d8("Channel closed");(0,window.isNaN)(this.C)?r6(!0):r6();this.dispose()};
g.h.vO=function(a){r6();(0,window.isNaN)(this.G())?(d8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,d8("Channel error: "+a+" with reconnection in "+this.G()+" ms"),e8(this,2))};
g.h.wO=function(a){a.params?d8("Received: action="+a.action+", params="+g.wg(a.params)):d8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.ex(a.params.devices);this.o=(0,g.H)(a,function(a){return new f6(a)});
a=!!g.eb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
RAa(this,a);break;case "loungeScreenDisconnected":g.sb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
RAa(this,!1);break;case "remoteConnected":var b=new f6(g.ex(a.params.device));g.eb(this.o,function(a){return b?a.id==b.id:!1})||g.pb(this.o,b);
break;case "remoteDisconnected":b=new f6(g.ex(a.params.device));g.sb(this.o,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":TAa(this,a);break;case "nowPlaying":VAa(this,a);break;case "onStateChange":UAa(this,a);break;case "onAdStateChange":WAa(this,a);break;case "onVolumeChanged":XAa(this,a);break;case "onSubtitlesTrackChanged":SAa(this,a);break;case "nowAutoplaying":YAa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.T("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.T("autoplayModeChange",this.B);"DISABLED"==this.B&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":ZAa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:d8("Unrecognized action: "+a.action)}};
g.h.RS=function(){if(this.A){var a=this.A;this.A=null;this.bb.videoId!=a&&i8(this,"getNowPlaying")}};
c8.prototype.subscribe=c8.prototype.subscribe;c8.prototype.unsubscribeByKey=c8.prototype.Hd;c8.prototype.ea=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.G())?a7(this.g)&&(0,window.isNaN)(this.C)&&(a=1):a=2);return a};
c8.prototype.getProxyState=c8.prototype.ea;c8.prototype.D=function(a){d8("Disconnecting with "+a);f8(this);this.T("beforeDisconnect",a);1==a&&r6();$za(this.g,a);this.dispose()};
c8.prototype.disconnect=c8.prototype.D;c8.prototype.da=function(){var a=this.bb;this.A&&(a=this.bb.clone(),T7(a,this.A,a.index));return U7(a)};
c8.prototype.getPlayerContextData=c8.prototype.da;
c8.prototype.la=function(a){var b=new O7(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.A=b.videoId,g.WD(this.I),this.I=g.UD((0,g.z)(this.RS,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&S7(this.bb)==S7(b)&&g.wg(this.bb.o)==g.wg(b.o)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.G)(c,function(a){this.T(a)},this)};
c8.prototype.setPlayerContextData=c8.prototype.la;c8.prototype.X=function(){var a=this.g.D.id,b=g.eb(this.o,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
c8.prototype.getOtherConnectedRemoteId=c8.prototype.X;c8.prototype.G=function(){var a=this.g;return a.o.isActive()?a.o.o-(0,g.F)():window.NaN};
c8.prototype.getReconnectTimeout=c8.prototype.G;c8.prototype.aa=function(){return this.B||"UNSUPPORTED"};
c8.prototype.getAutoplayMode=c8.prototype.aa;c8.prototype.ca=function(){return this.F||""};
c8.prototype.getAutoplayVideoId=c8.prototype.ca;c8.prototype.pa=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.o;g.Yt(a.g);a.start()}};
c8.prototype.reconnect=c8.prototype.pa;c8.prototype.ga=function(a,b){i8(this,a,b);QAa(this)};
c8.prototype.sendMessage=c8.prototype.ga;g.A(j8,j7);g.h=j8.prototype;g.h.fe=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.up=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.dd.$_ubk(this.o[a]);this.o.length=0;this.dd=null;j8.Y.W.call(this)};
g.h.gU=function(){this.T("screenChange")};
g.h.rQ=function(){this.T("onlineScreenChange")};
s7.prototype.$_st=s7.prototype.start;s7.prototype.$_gspc=s7.prototype.hU;s7.prototype.$_gsppc=s7.prototype.BD;s7.prototype.$_c=s7.prototype.contains;s7.prototype.$_g=s7.prototype.get;s7.prototype.$_a=s7.prototype.add;s7.prototype.$_un=s7.prototype.up;s7.prototype.$_r=s7.prototype.remove;s7.prototype.$_gs=s7.prototype.fe;s7.prototype.$_gos=s7.prototype.AD;s7.prototype.$_s=s7.prototype.subscribe;s7.prototype.$_ubk=s7.prototype.Hd;var k8=null,l8=null,e9=null,p8=[];g.p(f9,g.L);g.h=f9.prototype;
g.h.W=function(){g.L.prototype.W.call(this);this.B.stop();this.C.stop();this.L.stop();this.O();this.g.unsubscribe("proxyStateChange",this.yB,this);this.g.unsubscribe("remotePlayerChange",this.Fl,this);this.g.unsubscribe("remoteQueueChange",this.Io,this);this.g.unsubscribe("autoplayUpNext",this.XA,this);this.g.unsubscribe("previousNextChange",this.vB,this);this.g.unsubscribe("nowAutoplaying",this.nB,this);this.g.unsubscribe("autoplayDismissed",this.WA,this);this.g=this.G=null};
g.h.Hz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=X7(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":X7(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.lj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.bv(this.o.fa(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.o.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.bv(this.o.fa(1).videoId,c)}};
g.h.rO=function(a){this.L.JH(a)};
g.h.GT=function(a){this.Hz("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.RC=function(){var a=this.o.xc("captions","track");g.Xb(a)||j9(this,a)};
g.h.lB=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Fl,this);var b=Math.round(a.volume);a=!!a.muted;var c=X7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.N.start();this.g.subscribe("remotePlayerChange",this.Fl,this)}};
g.h.KP=function(){g.Xb(this.D)||kBa(this,this.D);this.F=!1};
g.h.yB=function(a,b){this.C.stop();2==b&&this.OC()};
g.h.Fl=function(){if(i9(this)){this.B.stop();var a=X7(this.g);switch(a.g){case 1081:case 1:h9(this,new g.hO(8));this.NC();break;case 1085:case 3:h9(this,new g.hO(9));break;case 1083:case 0:h9(this,new g.hO(2));this.J.stop();g9(this,this.o.fa().lengthSeconds);break;case 1084:h9(this,new g.hO(4));break;case 2:h9(this,new g.hO(4));g9(this,S7(a));break;case -1:h9(this,new g.hO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},h9(this,new g.hO(128,a))}a=X7(this.g).o;
var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,kBa(this,a));a=X7(this.g);-1==a.volume||Math.round(this.o.getVolume())==a.volume&&this.o.isMuted()==a.muted||this.N.isActive()||this.pD()}else jBa(this)};
g.h.vB=function(){this.o.T("mdxpreviousnextchange")};
g.h.Io=function(){i9(this)||jBa(this)};
g.h.SG=function(){this.g.Xw()};
g.h.XA=function(a){a&&(a=g.jE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.LR,this)}))&&(this.O=(0,g.z)(a.abort,a))};
g.h.LR=function(a,b){var c=new g.jN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.o.T("mdxautoplayupnext",c)};
g.h.nB=function(a){(0,window.isNaN)(a)||this.o.T("mdxnowautoplaying",a)};
g.h.WA=function(){this.o.T("mdxautoplaycanceled")};
g.h.cL=function(a,b){-1==X7(this.g).g?k9(this,a):b&&this.g.yD(a)};
g.h.pD=function(){if(i9(this)){var a=X7(this.g);this.A.Ea(this.R);a.muted?this.o.mute():this.o.Yf();this.o.setVolume(a.volume);this.R=this.A.P(this.o,"onVolumeChange",this.lB)}};
g.h.NC=function(){this.B.stop();if(!this.g.ia()){var a=X7(this.g);a.jb()&&h9(this,new g.hO(8));g9(this,S7(a));this.B.start()}};
g.h.OC=function(){this.C.stop();this.B.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.C.start()};g.p(l9,g.Y);l9.prototype.B=function(a){mBa(this,a.state)};g.p(m9,g.e_);m9.prototype.J=function(){var a=this.o.xc("remote","receivers");a&&1<a.length&&!this.o.xc("remote","quickCast")?(this.G=g.Gb(a,this.C,this),g.f_(this,(0,g.H)(a,this.C)),a=this.o.xc("remote","currentReceiver"),this.qf(this.C(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.C=function(a){return a.key};
m9.prototype.pf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
m9.prototype.rd=function(a){g.e_.prototype.rd.call(this,a);this.o.Fd("remote","currentReceiver",this.G[a]);this.B.Mb()};g.p(n9,g.IU);g.h=n9.prototype;g.h.create=function(){dBa(g.EL(g.X(this.g)));this.D.push(g.LF("yt-remote-before-disconnect",this.nO,this));this.D.push(g.LF("yt-remote-connection-change",this.UQ,this));this.D.push(g.LF("yt-remote-receiver-availability-change",this.wB,this));this.D.push(g.LF("yt-remote-auto-connect",this.SQ,this));this.D.push(g.LF("yt-remote-receiver-resumed",this.RQ,this));this.wB()};
g.h.load=function(){this.g.kt();g.IU.prototype.load.call(this);this.C=new f9(this,this.g,this.o);var a=(a=iBa())?a.currentTime:0;var b=d9()?new W7(X8(),void 0):null;0==a&&b&&(a=S7(X7(b)));0!=a&&(this.I=a||0,this.g.T("progresssync",a,void 0));lBa(this,this.F,this.F);g.a0(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.B=this.A;g.We(this.C,this.o);this.o=this.C=null;g.IU.prototype.unload.call(this);g.a0(this.g.app,5)};
g.h.W=function(){g.MF(this.D);g.IU.prototype.W.call(this)};
g.h.ol=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.Hz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.FH=function(){return this.loaded?this.C.suggestion:null};
g.h.Lf=function(){return this.o?X7(this.o).Lf:!1};
g.h.hasNext=function(){return this.o?X7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.FK=function(){var a=X7(this.o),b=this.g.fa();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+Q7(a):a.B,isPeggedToLive:1>=(a.D?a.A+Q7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+Q7(a):a.A,seekableStart:0<a.C?a.C+Q7(a):a.C}};
g.h.GK=function(){this.o&&this.o.wD()};
g.h.HK=function(){this.o&&this.o.xD()};
g.h.nO=function(a){1==a&&(this.J=this.o?X7(this.o):null)};
g.h.UQ=function(){var a=d9()?new W7(X8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ve(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.fa().videoId&&this.g.Oz(a.videoId,S7(a)));this.g.T("videodatachange","newdata",this.g.fa(),3)};
g.h.wB=function(){this.G=[this.A].concat(fBa());var a=$8()||this.A;o9(this,a);this.g.ua("onMdxReceiversChange")};
g.h.SQ=function(){var a=$8();o9(this,a)};
g.h.RQ=function(){this.B=$8()};
g.h.EK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?M7():o9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&M7(),!0):!1}};
g.h.IK=function(){a8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.td=function(){return!1};g.hY.remote=n9;})(_yt_player);
