(function(e,d,y){function p(h){for(var f={},k,a,w=0;w<h.length;w++)a=h[w],k=a.r+a.s+a.m,a.c&&(f[k]||(f[k]=[]),f[k].push(h[w]));return f}function u(h){for(var f=1;f<arguments.length;f++){var k=arguments[f];try{if(k.isSupported)return k.send(h)}catch(a){}}}function g(){if(c.length){for(var h=0;h<m.length;h++)m[h]();a._flhs+=1;n();u(p(c.splice(0,c.length)),z,I,G)}L=F=0}function n(){q&&l({k:"chk",f:a._flhs,l:a._lpn,s:"full"},"csm")}function l(h,f,k){k=k||{};0===k.bf&&a.isBF||(h={r:k.r||a.rid,s:k.s||e.ue_sid,
m:k.m||e.ue_mid,mkt:k.mkt||e.ue_mkt,sn:k.sn||e.ue_sn,c:f,d:h,t:k.t||a.d(),cs:k.c&&e.ue_qsl},a._lpn[f]=(a._lpn[f]||0)+1,k.b?u(p([h]),z,G):k.nb?u(p([h]),z,I,G):k.img||Q[f]?u(p([h]),G):k.ff?(c.push(h),g()):k.n?(c.push(h),0===M?g():L||(L=d.setTimeout(g,M))):(c.push(h),F||(F=d.setTimeout(g,J))))}function v(h,f,k){K++;K==C&&l({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr");(K<C||k&&k.il)&&l(h,f,k)}function D(){if(!N){for(var h=0;h<t.length;h++)t[h]();
for(h=0;h<m.length;h++)m[h]();a._flhs+=1;n();u(p(c.splice(0,c.length)),z,G);N=!0}}var x={};(function(){function h(f){return 10>f?"0"+f:f}function f(f){a.lastIndex=0;return a.test(f)?'"'+f.replace(a,function(f){var k=e[f];return"string"===typeof k?k:"\\u"+("0000"+f.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+f+'"'}function k(h,a){var e,E,r,z,R=w,T,d=a[h];d&&"object"===typeof d&&"function"===typeof d.toJSON&&(d=d.toJSON(h));"function"===typeof c&&(d=c.call(a,h,d));switch(typeof d){case "string":return f(d);
case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";w+=b;T=[];if("[object Array]"===Object.prototype.toString.apply(d)){z=d.length;for(e=0;e<z;e+=1)T[e]=k(e,d)||"null";r=0===T.length?"[]":w?"[\n"+w+T.join(",\n"+w)+"\n"+R+"]":"["+T.join(",")+"]";w=R;return r}if(c&&"object"===typeof c)for(z=c.length,e=0;e<z;e+=1)"string"===typeof c[e]&&(E=c[e],(r=k(E,d))&&T.push(f(E)+(w?": ":":")+r));else for(E in d)Object.prototype.hasOwnProperty.call(d,
E)&&(r=k(E,d))&&T.push(f(E)+(w?": ":":")+r);r=0===T.length?"{}":w?"{\n"+w+T.join(",\n"+w)+"\n"+R+"}":"{"+T.join(",")+"}";w=R;return r}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(f){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+h(this.getUTCMonth()+1)+"-"+h(this.getUTCDate())+"T"+h(this.getUTCHours())+":"+h(this.getUTCMinutes())+":"+h(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(f){return this.valueOf()});
var a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,w,b,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},c;"function"!==typeof x.stringify&&(x.stringify=function(f,h,a){var e;b=w="";if("number"===typeof a)for(e=0;e<a;e+=1)b+=" ";else"string"===typeof a&&(b=a);if((c=h)&&"function"!==typeof h&&("object"!==typeof h||"number"!==typeof h.length))throw Error("JSON.stringify");return k("",{"":f})})})();
var A=function(){function h(f,k){if(null==f)return k.push("!n");if("number"===typeof f)return k.push("!"+f);if("string"===typeof f)return"\\"==f[f.length-1]?k.push("'"+f.replace(/'/g,"\\'")+"u005C'"):k.push("'"+f.replace(/'/g,"\\'")+"'");if("boolean"===typeof f)return k.push(f?"!t":"!f");if(f instanceof Array){k.push("*");for(var a=0;a<f.length;a++)h(f[a],k);return k.push(")")}if("object"==typeof f){k.push("(");for(a in f)f.hasOwnProperty(a)&&(k.push(a),h(f[a],k));return k.push(")")}return k.push("!n")}
return{stringify:function(f){var k=[];h(f,k);return k.join("")}}}(),O=e.ue_qsl||2E3,C=1E3,q=1===window.ue_ddq,B=function(){},H=d.JSON&&d.JSON.stringify||x&&x.stringify,b=A.stringify,a=e.ue||{},A=e.uet||B;(e.uet||B)("bb","ue_frst_v2",{wb:1});var r="//"+e.ue_furl+"/1/batch/1/OE/",c=[],t=[],m=[],N=!1,L,F,M=void 0===e.ue_hpfi?1E3:e.ue_hpfi,J=void 0===e.ue_lpfi?1E4:e.ue_lpfi,Q={"scheduled-delivery":1},K=0,I=function(){function h(){if(d.XDomainRequest){var f=new XDomainRequest;f.onerror=B;f.ontimeout=B;
f.onprogress=B;f.onload=B;f.timeout=0;return f}if(d.XMLHttpRequest){f=new XMLHttpRequest;if(!("withCredentials"in f))throw"";return f}if(d.ActiveXObject){for(var k=0;k<b.length&&!f;k++)try{f=new ActiveXObject(b[k]),b=[b[k]]}catch(h){}return f}}function f(f){for(var k=[],h=f[0]||{},b=0;b<f.length;b++){var E={};E[f[b].c]=f[b].d;k.push(E)}return{rid:h.r||a.rid,sid:h.s||e.ue_sid,mid:h.m||e.ue_mid,mkt:h.mkt||e.ue_mkt,sn:h.sn||e.ue_sn,reqs:k}}function k(k){var a=f(k),b=h();if(!b)throw"";b.onerror=function(){for(var f=
0;f<k.length;f++)c.push(k[f]);I.isSupported=!1};b.open("POST",r,!0);b.setRequestHeader&&b.setRequestHeader("Content-type","text/plain");b.send(H(a))}var b="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(f){for(var h in f)f.hasOwnProperty(h)&&f[h].length&&k(f[h])},buildPOSTBodyLog:f,isSupported:!0}}(),G=function(){return{send:function(h){for(var f in h)if(h.hasOwnProperty(f)){for(var k=h[f],E=k,w={},c=void 0,
z=0;z<E.length;z++)c=E[z].c,w[c]||(w[c]=[]),w[c].push(E[z]);var k=k[0]||{},E=k.sn||e.ue_sn,k=r+(k.m||e.ue_mid)+":"+(k.s||e.ue_sid)+":"+(k.r||a.rid)+(E?":"+E:""),E=[],c=k,z=[],d=void 0;for(d in w)if(w.hasOwnProperty(d))for(var P=0;P<w[d].length;P++){var m=w[d][P],t=encodeURIComponent((m.cs?b:H)(m.d));z.push({l:t,t:m.t,p:1,c:d,d:m.cs?"c":"j"})}w=z;z=void 0;d="$";for(m=0;m<w.length;){P=w[m];z!=P.c?(c+=d+P.c+"=",d="&",z=P.c):c+=",";var t=c,l=P.d+":",g=P,c=(g.l.match(".{1,"+(O-c.length)+"}[^%]{0,2}")||
[])[0]||"";g.l=g.l.substr(c.length);c=t+(l+c+":"+P.t);if(P.l)c+=":"+P.p++ +"_",E.push(c),c=k,d="$",z=0;else if(m++,1!=P.p)for(c+=":"+P.p+"_"+P.p,t=0;t<P.p-1;t++)E[E.length-t-1]+=P.p}E.push(c);k=E;for(E=0;E<k.length;E++)(new Image).src=k[E]}},isSupported:!0}}(),z=function(){return{send:function(h){for(var f in h)if(h.hasOwnProperty(f)){var k=I.buildPOSTBodyLog(h[f]);if(!navigator.sendBeacon(r,H(k)))throw"";}},isSupported:!!navigator.sendBeacon}}();a._fic=G;a._fac=I;a._fbc=z;a._flq=c;a.sid=a.sid||e.ue_sid;
a.mid=a.mid||e.ue_mid;a.furl=a.furl||e.ue_furl;a.sn=a.sn||e.ue_sn;a.isBF=function(){var h=d.performance||d.webkitPerformance,f=y.ue_backdetect&&y.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,k=a.bfini;return h&&h.navigation&&2===h.navigation.type||1<k||!k&&1<f}();a._flhs=a._flhs||0;a._lpn=a._lpn||{};try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",B)}catch(S){e.ueLogError(S,{logLevel:"WARN"})}(function(){a.log&&
a.log.isStub&&(a.log.replay(function(h,f,k){var a=h[2]||{};a.t=f;a.r=k;a.n=1;v(h[0],h[1],a)}),a.onunload.replay(function(h){t.push(h[0])}),a.onflush.replay(function(h){m.push(h[0])}))})();a.log=v;a.log.reset=function(){K=0};a.onunload=function(h){t.push(h)};a.onflush=function(h){m.push(h)};a.attach("beforeunload",D);a.attach("pagehide",D);A("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(e,d){function y(b){if(b)return b.replace(/^\s+|\s+$/g,"")}function p(b,a){if(!b)return{};var r="INFO"===a.logLevel;b.m&&b.m.message&&(b=b.m);var c=a.m||a.message||"",c=b.m&&b.m.message?c+b.m.message:b.m&&b.m.target&&b.m.target.tagName?c+("Error handler invoked by "+b.m.target.tagName+" tag"):b.m?c+b.m:b.message?c+b.message:c+"Unknown error",c={m:c,name:b.name,type:b.type,csm:O+" "+(b.fromOnError?"onerror":"ueLogError")},d,m,g=0,l;c.logLevel=a.logLevel||v;a.adb&&(c.adb=a.adb);if(d=a.attribution)c.attribution=
""+d;if(!r){c.pageURL=a.pageURL||""+(window.location?window.location.href:"")||"missing";c.f=b.f||b.sourceURL||b.fileName||b.filename||b.m&&b.m.target&&b.m.target.src;c.l=b.l||b.line||b.lineno||b.lineNumber;c.c=b.c?""+b.c:b.c;c.s=[];c.t=e.ue.d();if((r=b.stack||(b.err?b.err.stack:""))&&r.split)for(c.csm+=" stack",d=r.split("\n");g<d.length&&c.s.length<C;)(r=d[g++])&&c.s.push(y(r));else for(c.csm+=" callee",m=u(b.args||arguments,"callee"),d=g=0;m&&g<C;)l=q,m.skipTrace||(r=m.toString())&&r.substr&&(l=
0===d?4*q:l,l=1==d?2*q:l,c.s.push(r.substr(0,l)),d++),m=u(m,"caller"),g++;if(!c.f&&0<c.s.length&&(g=c)&&g.s){var n,r=0<g.s.length?g.s[0]:"";d=1<g.s.length?g.s[1]:"";r&&(n=r.match(H));n&&3==n.length||!d||(n=d.match(B));n&&3==n.length&&(g.f=n[1],g.l=n[2])}}return c}function u(b,a){try{return b[a]}catch(e){}}function g(b,a){if(b){var r=p(b,a);e.ue.log(r,a.channel||l,{nb:1});"function"===typeof ue_err.elh&&ue_err.elh(b,a);try{if(!b.fromOnError){var c=d.console,t=d.JSON,m="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(c){if(t&&t.stringify)try{m+=t.stringify(r)}catch(g){m+="no info provided; converting to string failed"}else m+=r.m;"function"===typeof c.error?c.error(m,r):"function"===typeof c.log&&c.log(m,r)}}}catch(n){}}}function n(b,a){if(b&&!(e.ue_err.ec>e.ue_err.mxe)){e.ue_err.ter.push(b);a=a||{};var r=b.logLevel||a.logLevel;a.logLevel=r;a.attribution=b.attribution||a.attribution;r&&r!==v&&r!==D&&r!==x&&r!==A||e.ue_err.ec++;r&&r!=v||ue_err.ecf++;g(b,a)}}if(!e.ueLogError||e.ueLogError.isStub){var l=e.ue_err_chan||
"jserr",v="FATAL",D="ERROR",x="WARN",A="DOWNGRADED",O="v5",C=20,q=256,B=/\(?([^\s]*):(\d+):\d+\)?/,H=/.*@(.*):(\d*)/;g.skipTrace=1;p.skipTrace=1;n.skipTrace=1;(function(){if(e.ue_err.erl){var b=e.ue_err.erl.length,a,r;for(a=0;a<b;a++)r=e.ue_err.erl[a],g(r.ex,r.info);ue_err.erl=[]}})();e.ueLogError=n}})(ue_csm,window);
ue_csm.ue.exec(function(e,d){var y=function(){},p=function(){return{send:function(e,n){if(n&&e){var l;if(d.XDomainRequest)l=new XDomainRequest,l.onerror=y,l.ontimeout=y,l.onprogress=y,l.onload=y,l.timeout=0;else if(d.XMLHttpRequest){if(l=new XMLHttpRequest,!("withCredentials"in l))throw"";}else l=void 0;if(!l)throw"";l.open("POST",e,!0);l.setRequestHeader&&l.setRequestHeader("Content-type","text/plain");l.send(n)}},isSupported:!0}}(),u=function(){return{send:function(e,d){if(e&&d&&!navigator.sendBeacon(e,
d))throw"";},isSupported:!!navigator.sendBeacon}}();e.ue._ajx=p;e.ue._sBcn=u},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(e,d){function y(){for(var f=0;f<arguments.length;f++){var k=arguments[f];try{var h;if(k.isSupported){var a=S.buildPayload(t,r);h=k.send(b,a)}else throw dummyException;return h}catch(e){}}B({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr")}function p(){if(r.length){for(var f=0;f<J.length;f++)J[f]();y(q._sBcn||{},q._ajx||{});r=[];c={};t={};K=I=m=N=0}}function u(){var f=new Date,k=function(f){return 10>
f?"0"+f:f};return Date.prototype.toISOString?f.toISOString():f.getUTCFullYear()+"-"+k(f.getUTCMonth()+1)+"-"+k(f.getUTCDate())+"T"+k(f.getUTCHours())+":"+k(f.getUTCMinutes())+":"+k(f.getUTCSeconds())+"."+String((f.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function g(f){try{return JSON.stringify(f)}catch(k){}return null}function n(f,k,h,a){var b=!1;a=a||{};F++;F==x&&B({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},d.ue_err_chan||
"jserr");var c;if(c=!(F>=x))(c=f&&-1<f.constructor.toString().indexOf("Object")&&k&&-1<k.constructor.toString().indexOf("String")&&h&&-1<h.constructor.toString().indexOf("String"))||L++;c&&(f.producerId=f.producerId||k,f.schemaId=f.schemaId||h,f.timestamp=u(),k=Date.now?Date.now():+new Date,f.messageId=e.ue_id+"-"+k+"-"+F,a&&!a.ssd&&(f.sessionId=f.sessionId||e.ue_sid,f.requestId=f.requestId||e.ue_id,f.obfuscatedMarketplaceId=f.obfuscatedMarketplaceId||e.ue_mid),(k=g(f))?(k=k.length,(r.length==A||
m+k>O)&&p(),m+=k,f={data:S.compressEvent(f)},r.push(f),(a||{}).n?0===G?p():K||(K=d.setTimeout(p,G)):I||(I=d.setTimeout(p,z)),b=!0):b=!1);!b&&e.ue_int&&console.error("Invalid JS Nexus API call");return b}function l(){if(!Q){for(var f=0;f<M.length;f++)M[f]();for(f=0;f<J.length;f++)J[f]();r.length&&y(q._sBcn||{});Q=!0}}function v(f){M.push(f)}function D(f){J.push(f)}var x=1E3,A=499,O=524288,C=function(){},q=e.ue||{},B=q.log||C,H=e.uex||C;(e.uet||C)("bb","ue_sushi_v1",{wb:1});var b=e.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",
a=["messageId","timestamp"],r=[],c={},t={},m=0,N=0,L=0,F=0,M=[],J=[],Q=!1,K,I,G=void 0===e.ue_hpsi?1E3:e.ue_hpsi,z=void 0===e.ue_lpsi?1E4:e.ue_lpsi,S=function(){function f(f){c[f]="#"+N++;t[c[f]]=f;return c[f]}function k(f){if(f)switch(typeof f){case "number":return!(isNaN(f)||Infinity===f)&&f.toString().length>("#"+N).length;case "boolean":break;case "string":return f.length>("#"+N).length;default:return!0}return!1}function h(w){if(k(w)){var b=0;w instanceof Array?b=2:w instanceof Function?b=0:w instanceof
Object&&(b=1);switch(b){case 0:w=c[w]?c[w]:f(w);break;case 2:var e=w;w=[];for(var b=e.length,r=0;r<b;r++)w[r]=h(e[r]);break;case 1:b={};for(e in w)w.hasOwnProperty(e)&&(b[c[e]?c[e]:f(e)]=-1==a.indexOf(e)?h(w[e]):w[e]);w=b}}return w}return{compressEvent:h,buildPayload:function(){return g({cs:{dct:t},events:r})}}}();(function(){q.event&&q.event.isStub&&(q.event.replay(function(f){f[3]=f[3]||{};f[3].n=1;n.apply(this,f)}),q.onSushiUnload.replay(function(f){v(f[0])}),q.onSushiFlush.replay(function(f){D(f[0])}))})();
q.attach("beforeunload",l);q.attach("pagehide",l);q._cmps=S;q.event=n;q.event.reset=function(){F=0};q.onSushiUnload=v;q.onSushiFlush=D;try{d.P&&d.P.register&&d.P.register("sushi-client",C)}catch(h){e.ueLogError(h,{logLevel:"WARN"})}H("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);