(function(e){var c=window.AmazonUIPageJS||window.P,l=c._namespace||c.attributeErrors,a=l?l("AmazonGatewayHerotatorJS"):c;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,c,l){e.when("generic-observable").register("gw-herotator-controller",function(a){var c=function(){};return function(e){function h(){r.notifyObservers("delayBegin")}function g(){r.notifyObservers("delayInterrupted")}function k(b){for(var d=0;d<z.length;d++)if(z[d]===b)return d+1}function b(b){b=
b||{};return{delay_complete:b.delay_complete||c,js_ready:b.js_ready||c,fg_loaded:b.fg_loaded||c,mouse_move:b.mouse_move||c,mouse_leave:b.mouse_leave||c,delay_interrupted_timeout:b.delay_interrupted_timeout||c,rotation_complete:b.rotation_complete||c,goto_card:function(b){b!==C&&n.user_navigation(z[b-1])},user_navigation:b.user_navigation||function(b){n=new u(b)},user_interaction:b.user_interaction||function(){n.user_navigation(z[C-1])},stop_autorotation:b.stop_autorotation||function(){n.user_navigation(z[C-
1])},pause:b.pause||c,resume:b.resume||c}}function f(){function d(){!a&&D[f]&&(n=1===A?new y:new l)}h();var f=z[(C-1+1)%A+1-1],a=!0;return new b({fg_loaded:function(b){b===f&&d()},delay_complete:function(){a=!1;d()},mouse_move:function(){n=new q},pause:function(){n=new t}})}function q(){g();return new b({mouse_move:g,mouse_leave:function(){n=new f},delay_interrupted_timeout:function(){n.mouse_leave()},pause:function(){n=new t(!0)}})}function t(d){g();return new b({mouse_move:function(){d=!0;g()},
mouse_leave:function(){d=!1},resume:function(){n=d?new q:0<H?new f:new y}})}function l(){r.notifyObservers("autorotating");C=(C-1+1)%A+1;r.notifyObservers("gotoCard",C);H--;return new b({rotation_complete:function(){n=0<H?new f:new y},mouse_move:function(){n=0<H?new d:new y},pause:function(){n=new x}})}function d(d){var f=!1;return new b({rotation_complete:function(){h();n=f?new t:new q},pause:function(){f=!0},resume:function(){f=!1}})}function x(){var d=!1;return new b({rotation_complete:function(){h();
n=new t(d)},mouse_move:function(){d=!0},mouse_leave:function(){d=!1}})}function u(d){r.notifyObservers("userNavigation");C=k(d);r.notifyObservers("gotoCard",C);return new b({rotation_complete:function(){n=new y},user_navigation:function(b){n=new B(b)},user_interaction:c})}function B(d){return new b({rotation_complete:function(){n=new u(d)},user_navigation:function(b){d=b},user_interaction:c})}function y(){r.notifyObservers("stopAutorotation");return new b({})}e=e||{};var r=new a,n=new function(){function d(){D[E]&&
a&&(r.notifyObservers("ready"),n=new f,h&&n.pause(),g&&n.stop_autorotation())}var a=!1,g=!1,h=!1;return new b({fg_loaded:function(b){b===E&&d()},js_ready:function(){a=!0;d()},user_navigation:c,stop_autorotation:function(){g=!0},pause:function(){h=!0},resume:function(){h=!1}})},z=e.fgIDs||[],A=z.length,E=z[0],C=e.card_num||1,D={},H=e.circular?Infinity:A;return{delayComplete:function(){n.delay_complete()},jsReady:function(){n.js_ready()},fgLoaded:function(b){D[b]=!0;E===b&&r.notifyObservers("atfLoaded");
n.fg_loaded(b)},mouseMove:function(){n.mouse_move()},mouseLeave:function(){n.mouse_leave()},delayInterruptedTimeout:function(){n.delay_interrupted_timeout()},rotationComplete:function(){n.rotation_complete()},gotoCard:function(b){n.goto_card(b)},userInteraction:function(){n.user_interaction()},userNavigation:function(b){n.user_navigation(b)},stopAutorotation:function(){n.stop_autorotation()},pause:function(){n.pause()},resume:function(){n.resume()},addObserver:r.addObserver,removeObserver:r.removeObserver}}});
e.when("herotator-btf").register("herotator",function(a){return a});e.register("herotator-btf",function(){return function(a,p){function m(b){return function(){e.when("gw-desktop-herotator/controller").execute(function(){G[b]()})}}function h(b,d,f){b.addEventListener?b.addEventListener(d,f,!1):b.attachEvent("on"+d,f)}function g(b,f){A[b]=[];var a=f.length;if(0<a)for(var g=0;g<a;g++)(function(a){var g=new Image;g.onload=function(){A[b].splice(d(A[b],g),1);A[b]&&0===A[b].length&&
e.when("gw-desktop-herotator/controller").execute(function(){var d=document.getElementById("gw-ftGr-"+b),f=d.className,f=f.replace(/\s*\ba\-lazy\-loaded\b\s*/,"");d.className=f;G.fgLoaded(b)});e.when("A").execute(function(d){var f=d.$("#gw-ftGr-"+b+" img.a-dynamic-image");d.loadDynamicImage(f)})};A[b].push(g);g.src=f[a].src})(g);else e.when("gw-desktop-herotator/controller").execute(function(){G.fgLoaded(b)})}function k(){z=Date.now()}function b(){D||t()}function f(){I=I?Math.min(I,Date.now()):Date.now();
clearTimeout(r.timeout_id);clearTimeout(f.timeout_id);f.timeout_id=setTimeout(function(){f.timeout_id=0;G.delayInterruptedTimeout()},3E3)}function q(){D=!0}function t(){t.sent||(clearTimeout(t.timeout),t.timeout=setTimeout(function(){l(a.uri,a.data);t.sent=!0},2E3))}function l(b,d){e.when("A").execute(function(f){f.$.ajax(b,{async:!1,cache:!1,type:"post",data:d})})}function d(b,d){if(b.indexOf)return b.indexOf(d);for(var f=0;f<b.length;f++)if(b[f]===d)return f}function x(){return U=U||B()}function u(b){"object"===
typeof c.ue&&"function"===typeof c.ue.count&&c.ue.count(b,(c.ue.count(b)||0)+1)}function B(){var b=L(".a-carousel-rounded-buttons .a-carousel-left,.a-carousel-rounded-buttons .a-carousel-right");L(".a-carousel-rounded-buttons .a-carousel-left").attr("cel_widget_id","gw-desktop-hero-left-cel");L(".a-carousel-rounded-buttons .a-carousel-right").attr("cel_widget_id","gw-desktop-hero-right-cel");L(".a-carousel-rounded-buttons .a-carousel-left").addClass("celwidget");L(".a-carousel-rounded-buttons .a-carousel-right").addClass("celwidget");
L(".a-carousel-rounded-buttons .a-carousel-left").click(function(b){u("gw-desktop-hero-left")});L(".a-carousel-rounded-buttons .a-carousel-right").click(function(b){u("gw-desktop-hero-right")});return{show:function(){b.show();L(".a-carousel-left").css("z-index",10);L(".a-carousel-right").css("z-index",10)},hide:function(){b.hide()}}}function y(){var b=L("#gw-desktop-herotator");b.addClass("gw-desktop-herotator-ready");e.register("herotator-controls",function(){1<b.find(".a-carousel-card").length?
(x().show(),c.GWI&&c.GWI.recordLatency("gwHerotatorActive")):x().hide()})}function r(b){H<I&&(C-=I-H,I=0);H=Date.now();r.timeout_id=setTimeout(function(){C=E;G.delayComplete()},C)}function n(b,d){n.current_card!==d&&(n.current_card=d,w.gotoPage(d),S.notifyObservers("page_changed"));setTimeout(function(){G.rotationComplete()},250)}var z=Date.now(),A={},E=5E3,C=E,D=!1,H=0,I=0,w,L,K=document.getElementById("gw-desktop-herotator").getElementsByTagName("ol")[0],S,G,U;h(K,"click",m("userInteraction"));
h(K,"mouseenter",m("mouseMove"));h(K,"mousemove",m("mouseMove"));h(K,"mouseleave",m("mouseLeave"));h(K,"touchstart",m("userInteraction"));h(K,"touchmove",m("userInteraction"));h(K,"touchend",m("userInteraction"));h(K,"touchcancel",m("userInteraction"));for(var K=document.getElementById("gw-desktop-herotator").getElementsByTagName("li")[0],M=0,T=K.childNodes[M];T&&"div"!==String(T.nodeName).toLowerCase();)M++,T=K.childNodes[M];M=T;K=String(M.id).replace(/^gw-ftGr-/,"");M=M.getElementsByTagName("img");
g(K,M||[]);for(var N=[K],K=0;p[K];)N.push(p[K].fgID),K++;e.when("gw-herotator-controller").execute(function(d){G=new d({fgIDs:N});G.addObserver("atfLoaded",k);G.addObserver("delayBegin",r);G.addObserver("delayInterrupted",f);G.addObserver("gotoCard",n);G.addObserver("userNavigation",b);G.addObserver("stopAutorotation",q);G.addObserver("ready",function(){var b=Date.now()-z;C=Math.max(E-b,1);y();L("#gw-desktop-herotator").addClass("gw-desktop-herotator-ready")});e.register("gw-desktop-herotator/controller");
e.when("generic-observable").register("gw-desktop-herotator",function(b){S=new b;return{getAutorotationDelay:function(){return E},setAutorotationDelay:function(b){b=parseInt(b,10);C=b-(E-C);E=b},stopAutorotation:function(){G.stopAutorotation()},disableNavigation:function(){x().hide();w.pause()},enableNavigation:function(){x().show();w.resume()},pause:function(){G.pause()},resume:function(){G.resume()},addObserver:S.addObserver,removeObserver:S.removeObserver}})});e.when("A","a-carousel-framework",
"gwAjax").execute(function(b,d,f){function a(){var b=0;for(c.GWI&&c.GWI.recordLatency("gw-hero-btf-populate");p[b];){var d=p[b].fgID,f=p[b].content,n=document.getElementById("gw-ftGr-"+d);L(n).html(f);f=n.getElementsByTagName("img");g(d,f);b++}}L=b.$;d.onInit("gateway-desktop-layout.herotator",function(){var g=b.$("#gw-desktop-herotator > .a-carousel-container");w=d.getCarousel(g);w.onChange("pageNumber",function(){var b=w.getAttr("pageNumber");G.gotoCard(b);b-=2;p[b]&&p[b].callbackUrl&&(f(p[b].callbackUrl,
{type:"POST",id:"desktop-herotator-btf-"+p[b].fgID}),delete p[b].callbackUrl)});a();e.when("gw-desktop-herotator").register("gw-desktop-herotator/dom-ready");e.when("gw-desktop-herotator/controller","gw-desktop-herotator").execute(function(){G.jsReady()})})})}})});