(function(a,c,u){function r(a){for(var b={},e,p,d=0;d<a.length;d++)p=a[d],e=p.r+p.s+p.m,p.c&&(b[e]||(b[e]=[]),b[e].push(a[d]));return b}function q(a){for(var b=1;b<arguments.length;b++){var e=arguments[b];try{if(e.isSupported)return e.send(a)}catch(p){}}}function h(){for(var a=0;a<f.length;a++)f[a]();B.length&&q(r(B.splice(0,B.length)),M,L,G);E=I=0}function m(x,b,e){e=e||{};0===e.bf&&d.isBF||(x={r:e.r||d.rid,s:e.s||a.ue_sid,m:e.m||a.ue_mid,mkt:e.mkt||a.ue_mkt,sn:e.sn||a.ue_sn,c:b,d:x,t:e.t||d.d(),
cs:e.c&&a.ue_qsl},e.b?q(r([x]),M,G):e.nb?q(r([x]),M,L,G):e.img||K[b]?q(r([x]),G):e.ff?(B.push(x),h()):e.n?(B.push(x),0===N?h():E||(E=c.setTimeout(h,N))):(B.push(x),I||(I=c.setTimeout(h,J))))}function A(a,b,e){H++;H==w&&m({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},c.ue_err_chan||"jserr");(H<w||e&&e.il)&&m(a,b,e)}function n(){if(!F){for(var a=0;a<l.length;a++)l[a]();for(a=0;a<f.length;a++)f[a]();q(r(B.splice(0,B.length)),M,G);F=!0}}var k={};(function(){function a(e){return 10>
e?"0"+e:e}function b(a){p.lastIndex=0;return p.test(a)?'"'+a.replace(p,function(a){var e=z[a];return"string"===typeof e?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,p){var x,z,c,v,n=d,g,C=p[a];C&&"object"===typeof C&&"function"===typeof C.toJSON&&(C=C.toJSON(a));"function"===typeof f&&(C=f.call(p,a,C));switch(typeof C){case "string":return b(C);case "number":return isFinite(C)?String(C):"null";case "boolean":case "null":return String(C);case "object":if(!C)return"null";
d+=l;g=[];if("[object Array]"===Object.prototype.toString.apply(C)){v=C.length;for(x=0;x<v;x+=1)g[x]=e(x,C)||"null";c=0===g.length?"[]":d?"[\n"+d+g.join(",\n"+d)+"\n"+n+"]":"["+g.join(",")+"]";d=n;return c}if(f&&"object"===typeof f)for(v=f.length,x=0;x<v;x+=1)"string"===typeof f[x]&&(z=f[x],(c=e(z,C))&&g.push(b(z)+(d?": ":":")+c));else for(z in C)Object.prototype.hasOwnProperty.call(C,z)&&(c=e(z,C))&&g.push(b(z)+(d?": ":":")+c);c=0===g.length?"{}":d?"{\n"+d+g.join(",\n"+d)+"\n"+n+"}":"{"+g.join(",")+
"}";d=n;return c}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(e){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var p=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
d,l,z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},f;"function"!==typeof k.stringify&&(k.stringify=function(a,p,x){var z;l=d="";if("number"===typeof x)for(z=0;z<x;z+=1)l+=" ";else"string"===typeof x&&(l=x);if((f=p)&&"function"!==typeof p&&("object"!==typeof p||"number"!==typeof p.length))throw Error("JSON.stringify");return e("",{"":a})})})();var g=function(){function a(b,e){if(null==b)return e.push("!n");if("number"===typeof b)return e.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?e.push("'"+b.replace(/'/g,"\\'")+"u005C'"):e.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return e.push(b?"!t":"!f");if(b instanceof Array){e.push("*");for(var p=0;p<b.length;p++)a(b[p],e);return e.push(")")}if("object"==typeof b){e.push("(");for(p in b)b.hasOwnProperty(p)&&(e.push(p),a(b[p],e));return e.push(")")}return e.push("!n")}return{stringify:function(b){var e=[];a(b,e);return e.join("")}}}(),t=a.ue_qsl||2E3,w=1E3,y=function(){},v=c.JSON&&
c.JSON.stringify||k&&k.stringify,D=g.stringify,d=a.ue||{},g=a.uet||y;(a.uet||y)("bb","ue_frst_v2",{wb:1});var b="//"+a.ue_furl+"/1/batch/1/OE/",B=[],l=[],f=[],F=!1,E,I,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,J=void 0===a.ue_lpfi?1E4:a.ue_lpfi,K={"scheduled-delivery":1},H=0,L=function(){function x(){if(c.XDomainRequest){var a=new XDomainRequest;a.onerror=y;a.ontimeout=y;a.onprogress=y;a.onload=y;a.timeout=0;return a}if(c.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(c.ActiveXObject){for(var x=
0;x<e.length&&!a;x++)try{a=new ActiveXObject(e[x]),e=[e[x]]}catch(b){}return a}}function l(e){for(var x=[],b=e[0]||{},z=0;z<e.length;z++){var f={};f[e[z].c]=e[z].d;x.push(f)}return{rid:b.r||d.rid,sid:b.s||a.ue_sid,mid:b.m||a.ue_mid,mkt:b.mkt||a.ue_mkt,sn:b.sn||a.ue_sn,reqs:x}}var e="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var e in a)if(a.hasOwnProperty(e)&&a[e].length){var d=l(a[e]),z=x();
if(!z)throw"";z.open("POST",b,!0);z.setRequestHeader&&z.setRequestHeader("Content-type","text/plain");z.send(v(d))}},buildPOSTBodyLog:l,isSupported:!0}}(),G=function(){return{send:function(x){for(var l in x)if(x.hasOwnProperty(l)){for(var e=x[l],p=e,f={},c=void 0,z=0;z<p.length;z++)c=p[z].c,f[c]||(f[c]=[]),f[c].push(p[z]);var e=e[0]||{},p=e.sn||a.ue_sn,e=b+(e.m||a.ue_mid)+":"+(e.s||a.ue_sid)+":"+(e.r||d.rid)+(p?":"+p:""),p=[],c=e,z=[],n=void 0;for(n in f)if(f.hasOwnProperty(n))for(var O=0;O<f[n].length;O++){var g=
f[n][O],k=encodeURIComponent((g.cs?D:v)(g.d));z.push({l:k,t:g.t,p:1,c:n,d:g.cs?"c":"j"})}f=z;z=void 0;n="$";for(g=0;g<f.length;){O=f[g];z!=O.c?(c+=n+O.c+"=",n="&",z=O.c):c+=",";var k=c,B=O.d+":",h=O,c=(h.l.match(".{1,"+(t-c.length)+"}[^%]{0,2}")||[])[0]||"";h.l=h.l.substr(c.length);c=k+(B+c+":"+O.t);if(O.l)c+=":"+O.p++ +"_",p.push(c),c=e,n="$",z=0;else if(g++,1!=O.p)for(c+=":"+O.p+"_"+O.p,k=0;k<O.p-1;k++)p[p.length-k-1]+=O.p}p.push(c);e=p;for(p=0;p<e.length;p++)(new Image).src=e[p]}},isSupported:!0}}(),
M=function(){return{send:function(a){for(var d in a)if(a.hasOwnProperty(d)){var e=L.buildPOSTBodyLog(a[d]);if(!navigator.sendBeacon(b,v(e)))throw"";}},isSupported:!!navigator.sendBeacon}}();d._fic=G;d._fac=L;d._fbc=M;d._flq=B;d.sid=d.sid||a.ue_sid;d.mid=d.mid||a.ue_mid;d.furl=d.furl||a.ue_furl;d.sn=d.sn||a.ue_sn;d.isBF=function(){var a=c.performance||c.webkitPerformance,b=u.ue_backdetect&&u.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,e=d.bfini;return a&&a.navigation&&2===a.navigation.type||
1<e||!e&&1<b}();try{c.amznJQ&&c.amznJQ.declareAvailable&&c.amznJQ.declareAvailable("forester-client"),c.P&&c.P.register&&c.P.register("forester-client",y)}catch(P){a.ueLogError(P,{logLevel:"WARN"})}(function(){d.log&&d.log.isStub&&(d.log.replay(function(a,b,e){var p=a[2]||{};p.t=b;p.r=e;p.n=1;A(a[0],a[1],p)}),d.onunload.replay(function(a){l.push(a[0])}),d.onflush.replay(function(a){f.push(a[0])}))})();d.log=A;d.log.reset=function(){H=0};d.onunload=function(a){l.push(a)};d.onflush=function(a){f.push(a)};
d.attach("beforeunload",n);d.attach("pagehide",n);g("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,c){function u(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function r(b,c){if(!b)return{};var l="INFO"===c.logLevel;b.m&&b.m.message&&(b=b.m);var f=c.m||c.message||"",f=b.m&&b.m.message?f+b.m.message:b.m&&b.m.target&&b.m.target.tagName?f+("Error handler invoked by "+b.m.target.tagName+" tag"):b.m?f+b.m:b.message?f+b.message:f+"Unknown error",f={m:f,name:b.name,type:b.type,csm:w+" "+(b.fromOnError?"onerror":"ueLogError")},g,k,h=0,m;f.logLevel=c.logLevel||n;if(g=c.attribution)f.attribution=
""+g;if(!l){f.pageURL=c.pageURL||""+(window.location?window.location.href:"")||"missing";f.f=b.f||b.sourceURL||b.fileName||b.filename||b.m&&b.m.target&&b.m.target.src;f.l=b.l||b.line||b.lineno||b.lineNumber;f.c=b.c?""+b.c:b.c;f.s=[];f.t=a.ue.d();if((l=b.stack||(b.err?b.err.stack:""))&&l.split)for(f.csm+=" stack",g=l.split("\n");h<g.length&&f.s.length<y;)(l=g[h++])&&f.s.push(u(l));else for(f.csm+=" callee",k=q(b.args||arguments,"callee"),g=h=0;k&&h<y;)m=v,k.skipTrace||(l=k.toString())&&l.substr&&(m=
0===g?4*v:m,m=1==g?2*v:m,f.s.push(l.substr(0,m)),g++),k=q(k,"caller"),h++;if(!f.f&&0<f.s.length&&(h=f)&&h.s){var t,l=0<h.s.length?h.s[0]:"";g=1<h.s.length?h.s[1]:"";l&&(t=l.match(d));t&&3==t.length||!g||(t=g.match(D));t&&3==t.length&&(h.f=t[1],h.l=t[2])}}return f}function q(a,d){try{return a[d]}catch(l){}}function h(b,d){if(b){var l=r(b,d);a.ue.log(l,d.channel||A,{nb:1});"function"===typeof ue_err.eh&&ue_err.eh(b,d);try{if(!b.fromOnError){var f=c.console,v=c.JSON,n="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(f){if(v&&v.stringify)try{n+=v.stringify(l)}catch(g){n+="no info provided; converting to string failed"}else n+=l.m;"function"===typeof f.error?f.error(n,l):"function"===typeof f.log&&f.log(n,l)}}}catch(k){}}}function m(b,d){if(b&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ter.push(b);d=d||{};var l=b.logLevel||d.logLevel;d.logLevel=l;d.attribution=b.attribution||d.attribution;l&&l!==n&&l!==k&&l!==g&&l!==t||a.ue_err.ec++;l&&l!=n||ue_err.ecf++;h(b,d)}}if(!a.ueLogError||a.ueLogError.isStub){var A=a.ue_err_chan||
"jserr",n="FATAL",k="ERROR",g="WARN",t="DOWNGRADED",w="v5",y=20,v=256,D=/\(?([^\s]*):(\d+):\d+\)?/,d=/.*@(.*):(\d*)/;h.skipTrace=1;r.skipTrace=1;m.skipTrace=1;(function(){if(a.ue_err.erl){var b=a.ue_err.erl.length,d,l;for(d=0;d<b;d++)l=a.ue_err.erl[d],h(l.ex,l.info);ue_err.erl=[]}})();a.ueLogError=m}})(ue_csm,window);
(function(a,c){a.ue_cel||(a.ue_cel=function(){function u(a,c){c?c.r=w:c={r:w,c:1};c.clog&&k.clog?k.clog(a,c.ns||A,c):c.glog&&k.glog?k.glog(a,c.ns||A,c):k.log(a,c.ns||A,c)}function r(){var a=h.length;if(0<a){for(var c=[],d=0;d<a;d++){var b=h[d].api;b.ready()?(b.on({ts:k.d,ns:A}),m.push(h[d]),u({k:"mso",n:h[d].name,t:k.d()})):c.push(h[d])}h=c}}function q(){if(!q.executed){for(var a=0;a<m.length;a++)m[a].api.off&&m[a].api.off({ts:k.d,ns:A});u({k:"eod",t0:k.t0,t:k.d()},{c:1,il:1});q.executed=1;for(a=
0;a<m.length;a++)h.push(m[a]);m=[];clearTimeout(n)}}var h=[],m=[],A=a.ue_cel_ns||"cel",n,k=a.ue,g=a.uet,t=a.uex,w=k.rid,y=c.requestAnimationFrame||function(a){a()};if(k.isBF)u({k:"bft",t:k.d()});else return"function"==typeof g&&g("bb","csmCELLSframework",{wb:1}),setTimeout(r,0),k.onunload(q),n=setTimeout(q,6E5),"function"==typeof t&&t("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,c){h.push({name:a,api:c});u({k:"mrg",n:a,t:k.d()});r()},reset:function(a){u({k:"rst",t0:k.t0,t:k.d()});h=
h.concat(m);m=[];for(var c=h.length,d=0;d<c;d++)h[d].api.off(),h[d].api.reset();w=a||k.rid;r();clearTimeout(n);n=setTimeout(q,6E5);q.executed=0},timeout:function(a,n){return c.setTimeout(function(){y(a)},n)},log:u}}())})(ue_csm,window);
(function(a,c,u){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function r(){var d={w:m.width,aw:m.availWidth,h:m.height,ah:m.availHeight,cd:m.colorDepth,pd:m.pixelDepth},b={w:(u.body||{}).scrollWidth,h:(u.body||{}).scrollHeight};g&&g.w==d.w&&g.h==d.h&&g.aw==d.aw&&g.ah==d.ah&&g.pd==d.pd&&g.cd==d.cd||(g=d,g.t=n(),g.k="sci",y(g));t&&t.w==b.w&&t.h==b.h||(t=b,t.t=n(),t.k="doi",y(t));A=a.ue_cel.timeout(r,k)}function q(){y({k:"ebl",t:n()},{ff:1})}function h(){y({k:"efo",t:n()})}var m,A,n,k,g,t,w=a.ue,y=a.ue_cel.log,
v=a.uet,D=a.uex;"function"==typeof v&&v("bb","csmCELLSpdm",{wb:1});return{on:function(d){k=d.timespan||500;n=d.ts;m=c.screen;w.attach&&(w.attach("blur",q,c),w.attach("focus",h,c));d=c.location;y({k:"pmd",o:d.origin,p:d.pathname,t:n()});a.ue_cel.timeout(r,0);"function"==typeof D&&D("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(A);w.detach&&(w.detach("blur",q,c),w.detach("focus",h,c));w.count&&(w.count("cel.PDM.TotalExecutions",0),w.count("cel.PDM.TotalExecutionTime",0),w.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return u.body&&a.ue_cel&&a.ue_cel.log},reset:function(){g=t=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,c){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function u(){var a=A(),b={w:c.innerWidth,h:c.innerHeight,x:c.pageXOffset,y:c.pageYOffset};q&&q.w==b.w&&q.h==b.h&&q.x==b.x&&q.y==b.y||(b.t=a,b.k="vpi",q=b,t(q,{clog:1}));h=0;n=A()-a;k+=1}function r(){h||(h=a.ue_cel.timeout(u,m))}var q,h,m,A,n=0,k=0,g=a.ue,t=a.ue_cel.log,w=a.uet,y=a.uex,v=g.attach,D=g.detach;"function"==typeof w&&w("bb","csmCELLSvpm",{wb:1});return{on:function(d){A=d.ts;m=d.timespan||100;a.ue_cel.timeout(u,0);v&&(v("scroll",r),
v("resize",r));"function"==typeof y&&y("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(h);D&&(D("scroll",r),D("resize",r));g.count&&(g.count("cel.VPI.TotalExecutions",k),g.count("cel.VPI.TotalExecutionTime",n),g.count("cel.VPI.AverageExecutionTime",n/k))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=void 0},getVpi:function(){return q}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,c,u){if(!a.ue_fem){var r=a.ue||{};!r.isBF&&!a.ue_fem&&u.querySelector&&c.getComputedStyle&&[].forEach&&(a.ue_fem=function(){function q(a,e){return a>e?3>a-e:3>e-a}function h(a,e){var p=c.pageXOffset,x=c.pageYOffset,b;a:{try{if(a){var d=a.getBoundingClientRect();b={x:d.left+p|0,y:d.top+x|0,w:d.width|0,h:d.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else b=void 0;break a}catch(l){}b=void 0}if(b&&!a.cel_b)a.cel_b=b,B({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,
t:e,k:"ewi",cl:a.className},{clog:1});else{if(p=b)p=a.cel_b,x=b,p=x.d===p.d&&1===x.d?!1:!(q(p.x,x.x)&&q(p.y,x.y)&&q(p.w,x.w)&&q(p.h,x.h)&&p.d===x.d);p&&(a.cel_b=b,B({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:e,k:"ewi"},{clog:1}))}}function m(a,p){var x;x=a.c?u.getElementsByClassName(a.c):a.id?[u.getElementById(a.id)]:u.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<x.length;widgetIndex++){var d=x[widgetIndex];d&&(d.cel_n||(d.cel_n=d.getAttribute("cel_widget_id")||
(a.id_gen||b)(d,widgetIndex)||d.id),a.w.push(d),k(e,d,p))}}function A(a,e){l.contains(a)||B({n:a.cel_n,t:e,k:"ewd"},{clog:1})}function n(a){G.length&&ue_cel.timeout(function(){for(var e=S(),x=!1;S()-e<v&&!x;){for(x=P;0<x--&&0<G.length;){var b=G.shift();p[b.type](b.elem,b.time)}x=0===G.length}M++;n(a)},0)}function k(a,e,p){G.push({type:a,elem:e,time:p})}function g(a,e){for(var p=0;p<d.length;p++)for(var x=d[p].w||[],b=0;b<x.length;b++)k(a,x[b],e)}function t(){L||(L=a.ue_cel.timeout(function(){L=null;
var a=D();g(x,a);for(var e=0;e<d.length;e++)k(Q,d[e],a);n(a)},y))}function w(){L||H||(H=a.ue_cel.timeout(function(){H=null;var a=D();g(e,a);n(a)},y))}var y=50,v=4.5,D,d=[],b=function(){},B=a.ue_cel.log,l,f,F,E,I=c.MutationObserver||c.WebKitMutationObserver||c.MozMutationObserver,N=!!I,J,K,H,L,G=[],M=0,P=null,x="removedWidget",Q="updateWidgets",e="processWidget",p,R=c.performance||{},S=R.now&&function(){return R.now()}||function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});
return{on:function(e){function x(){if(F&&E&&l&&l.contains&&l.getBoundingClientRect&&D){p={removedWidget:A,updateWidgets:m,processWidget:h};if(N){var a={attributes:!0,subtree:!0};J=new I(w);K=new I(t);J.observe(l,a);K.observe(l,{childList:!0,subtree:!0});K.observe(f,a)}else F.call(l,"DOMAttrModified",w),F.call(l,"DOMNodeInserted",t),F.call(l,"DOMNodeRemoved",t),F.call(f,"DOMNodeInserted",w),F.call(f,"DOMNodeRemoved",w);t()}}l=u.body;f=u.head;F=l.addEventListener;E=l.removeEventListener;D=e.ts;d=a.cel_widgets||
[];P=e.bs||5;r.deffered?x():r.attach&&r.attach("load",x);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){F&&E&&l&&l.contains&&l.getBoundingClientRect&&D&&(K&&(K.disconnect(),K=null),J&&(J.disconnect(),J=null),E.call(l,"DOMAttrModified",w),E.call(l,"DOMNodeInserted",t),E.call(l,"DOMNodeRemoved",t),E.call(f,"DOMNodeInserted",w),E.call(f,"DOMNodeRemoved",w));r.count&&r.count("cel.widgets.batchesProcessed",M)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){d=a.cel_widgets||
[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))}})(ue_csm,window,document);
(function(a,c){a.ue_mcm||a.ue.isBF||(a.ue_mcm=function(){function u(a){try{if(a.id)return"//*[@id='"+a.id+"']";var c,g=1,h;for(h=a.previousSibling;h;h=h.previousSibling)h.nodeName==a.nodeName&&(g+=1);c=g;var m=a.nodeName;1!=c&&(m+="["+c+"]");a.parentNode&&(m=u(a.parentNode)+"/"+m);return m}catch(q){return"DETACHED"}}function r(a,k){var g=a.srcElement||a.target||{},m={k:q,w:(k||{}).ow||(c.body||{}).scrollWidth,h:(k||{}).oh||(c.body||{}).scrollHeight,t:(k||{}).ots||h(),x:a.pageX,y:a.pageY,p:u(g),n:g.nodeName};
a.button&&(m.b=a.button);g.href&&(m.r=g.href);g.id&&(m.i=g.id);g.className&&(m.c=g.className.split(/\s+/));A(m,{c:1})}var q="mcm",h,m=a.ue,A=a.ue_cel.log;return{on:function(n){h=n.ts;a.ue_cel_stub&&a.ue_cel_stub.replayModule(q,r);m.attach&&m.attach("click",r,c)},off:function(a){m.detach&&m.detach("click",r,c)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,c){a.ue_mmm||a.ue.isBF||(a.ue_mmm=function(u){function r(a,b){var d={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:k()};!b&&I&&(d.t-I.t<m||d.x==I.x&&d.y==I.y)||(I=d,f.push(d))}function q(){if(f.length){B=H.now();for(var a=0;a<f.length;a++){var c=f[a],g=a;N=f[E];J=c;var k=void 0;if(!(k=2>g)){a:if(f[g].t-f[g-1].t>h)k=0;else{for(k=E+1;k<g;k++){var x=N,Q=J,e=f[k];K=(Q.x-x.x)*(x.y-e.y)-(x.x-e.x)*(Q.y-x.y);if(K*K/((Q.x-x.x)*(Q.x-x.x)+(Q.y-x.y)*(Q.y-x.y))>A){k=0;break a}}k=1}k=!k}k?E=g-1:F.pop();F.push(c)}l=
H.now()-B;v=Math.min(v,l);D=Math.max(D,l);d=(d*b+l)/(b+1);b+=1;w({k:n,e:F,min:Math.floor(1E3*v),max:Math.floor(1E3*D),avg:Math.floor(1E3*d)},{c:1});f=[];F=[];E=0}}var h=100,m=20,A=25,n="mmm1",k,g,t=a.ue,w=a.ue_cel.log,y,v=1E3,D=0,d=0,b=0,B,l,f=[],F=[],E=0,I,N,J,K,H=u&&u.now&&u||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){k=a.ts;g=a.ns;t.attach&&t.attach("mousemove",r,c);y=setInterval(q,3E3)},off:function(a){g&&(I&&r(I,!0),q());clearInterval(y);t.detach&&t.detach("mousemove",
r,c)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){f=[];F=[];E=0;I=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);