//tealium universal tag - utag.176 ut4.0.201610072053, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.push_count=0;u.event_lookup={"add_to_cart":"add_to_cart","product_view":"product_view","reg":"reg","main":"main","landing":"landing"};u.map={"meta.article.id:user":"article_view"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//cdn.nanigans.com/NaN_tracker.js","app_id":"507255","fb_app_id":"","custom_mappings":{},"event_name":"","event_type":"","product_id":[],"product_quantity":[],"product_unit_price":[]};c=[],g={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("custom.")===0){u.data.custom_mappings[e[f].substring(7)]=b[d];}else{u.data[e[f]]=b[d];}}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){g=""+u.event_lookup[u.map[d]];if(g!==""){b._cevent=g;}}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";u.data.customer_id=u.data.customer_id||b._ccustid||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.event_name=u.data.event_name||b._cevent||"";var loadScript=true;if(typeof NaN_api!='undefined'&&NaN_api){loadScript=false;}else{window.NaN_api=[];}
var config=[];var key="";config.push(u.data.app_id);if(u.data.customer_id){config.push(u.data.customer_id);}
g={};for(key in u.data.custom_mappings){g[key]=u.data.custom_mappings[key];}
if(u.data.fb_app_id){g.fb_app_id=u.data.fb_app_id;}
if(u.data.order_id||u.data.event_type==="purchase"){u.data.event_name=u.data.event_name||"main";g.unique=u.data.order_id||""+b['cp.utag_main_ses_id']+b["cp.utag_main__st"];g.sku=u.data.product_id;g.qty=u.data.product_quantity;var valueArr=[];for(var i=0;i<u.data.product_id.length;i++){valueArr[i]=(parseFloat((u.data.product_unit_price[i]||0))*parseFloat((u.data.product_quantity[i]||1))).toFixed(2);}
if(u.data.order_currency){g.currency=u.data.order_currency;}
if(u.data.content_ids){g.content_ids=u.data.content_ids;}
NaN_api.push(config,["purchase",u.data.event_name,valueArr,g]);}else if(u.data.event_name==="add_to_cart"){g.sku=u.data.product_id[0];g.qty=u.data.product_quantity[0];var subtotal=(parseFloat(u.data.product_unit_price[0]||0)*parseFloat(u.data.product_quantity[0]||1)).toFixed(2);if(u.data.order_currency){g.currency=u.data.order_currency;}
if(u.data.content_ids){g.content_ids=u.data.content_ids;}
NaN_api.push(config,["user","add_to_cart",subtotal,g]);}else if(u.data.event_name==="product_view"){g.sku=u.data.product_id[0];if(u.data.content_ids!==""){g.content_ids=u.data.content_ids;}
NaN_api.push(config,["user","product_view",u.push_count,g]);u.push_count++;}else if(u.data.event_name==="reg"){NaN_api.push(config,["install","reg",u.push_count,g]);}else if(u.data.event_name!==""){u.data.event_type=u.data.event_type||"user";NaN_api.push(config,[u.data.event_type,u.data.event_name,u.push_count,g]);}else if(a==="view"){NaN_api.push(config,["visit","landing",u.push_count,g]);u.push_count++;}
if(loadScript){u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":'utag_176'});}
}};utag.o[loader].loader.LOAD(id);}("176","wsjdn.wsjpages"));}catch(error){utag.DB(error);}
